'''
    Alphabet.py - A collection of functions to help draw letters on an ASIC
                    
'''

from LpdDevice.LpdDevice import LpdDevice
from EthernetUtility import EthernetUtility 
import argparse, sys
from datetime import datetime

class Alphabet():
    
    def __init__(self, fileName=None):
        

        if fileName == None:
            raise Exception("Alphabet Object created without fileName argument!")
        else:
            self.file = open(fileName, "w")

    def horizontalLine(self, tile, asic, start, stop):
        '''
            Draws a straight line from 'start' until 'stop', targeting 'asic' and 'tile'
            Note: stop must be greater than start
        '''
        if not stop >= start:
            raise Exception("stop (%s) must be greater than start (%s) " % (stop, start))
        for index in range(0, 512, 16):
            lowerLimit = index
            upperLimit = index +16
            if (start >= lowerLimit and start < upperLimit) and (stop < lowerLimit or stop >= upperLimit):
                raise Exception("start (%s) not on same horizontal line as stop (%s) " % (start, stop))
        
        xmlString = '   <!-- Draw horizontal line between pixels %3s and %3s in tile: %2s asic: %s -->\n' % (start, stop, tile, asic)
        for pixel in range(start, stop+1):
#            xmlString += '   <mux_decoder tile="%s" asic="%s" pixel="%s" value="4"/>\n' % (tile, asic, pixel)
#
#        
            xmlString += '   <mux_decoder '
            if tile != None:
                xmlString += 'tile="%s" ' % tile
            if asic != None:
                xmlString += 'asic="%s" ' % asic

            xmlString += 'pixel="%s" value="4"/>\n' % pixel

        self.file.write( xmlString)        
        
    def verticalLine(self, tile, asic, start, stop):
        '''
            Draws a straight line from 'start' until 'stop', targeting 'asic' and 'tile'
            Note: stop must be greater than start
        '''
        if not stop >= start:
            raise Exception("stop (%s) must be greater than start (%s) " % (stop, start))
        if not (start % 16 and stop % 16):
                raise Exception("start (%s) not on same vertical line as stop (%s) " % (start, stop))

        xmlString = '   <!-- Draw vertical line between pixels %3s and %3s in tile: %2s asic: %s -->\n' % (start, stop, tile, asic)
        
        for pixel in range(start, stop+1, 16):
            xmlString += '   <mux_decoder '
            if tile != None:
                xmlString += 'tile="%s" ' % tile
            if asic != None:
                xmlString += 'asic="%s" ' % asic

            xmlString += 'pixel="%s" value="4"/>\n' % pixel

        self.file.write( xmlString)
        
    def singlePixel(self, tile, asic, pixel):
        '''
            Place a single pixel within a specified tile and ASIC
        '''
        if not ( -1 < pixel < 512):
            raise Exception("singlePixel() pixel (%s) outside valid range " % ( pixel))

        xmlString = '   <mux_decoder tile="%s" asic="%s" pixel="%s" value="4"/>\n' % (tile, asic, pixel)
        
        self.file.write( xmlString)

    def insertComment(self, comment):
        xmlString = '\n\n   <!-- COMMENT: %s -->\n' % (comment)
        
        self.file.write( xmlString)
        
        
    def __del__(self):
        self.file.close()
        
if __name__ == '__main__':

    a = Alphabet(fileName = "test.xml")
    a.insertComment( " This is the file generated by Alphabet.py and does not constitute a full, valid XML Setup Params XML file.")
    currentTime = str( datetime.now())
    a.insertComment( " This file generated on: %s" % currentTime)

#    # Draw 0 - On eight ASICs within one tile
#    (tile, asic) = (0, None)
#    a.insertComment( "Numeral 0")
#    (start, stop) = (115, 227)
#    a.verticalLine( tile, asic, start, stop)
#    (start, stop) = (119, 231)
#    a.verticalLine( tile, asic, start, stop)
#    (start, stop) = (132, 148)
#    a.verticalLine( tile, asic, start, stop)
#    (start, stop) = (165, 181)
#    a.verticalLine( tile, asic, start, stop)
#    (start, stop) = (198, 214)
#    a.verticalLine( tile, asic, start, stop)
#    (start, stop) = (100, 102)
#    a.horizontalLine( tile, asic, start, stop)
#    (start, stop) = (244, 246)
#    a.horizontalLine( tile, asic, start, stop)
#    

    # Draw 0 - On one ASIC of every tile
    (tile, asic) = (None, 0)
    a.insertComment( "Numeral 0")
    (start, stop) = (339, 451) #115, 227)
    a.verticalLine( tile, asic, start, stop)
    (start, stop) = (343, 455) #119, 231)
    a.verticalLine( tile, asic, start, stop)
    (start, stop) = (356, 372)#132, 148)
    a.verticalLine( tile, asic, start, stop)
    (start, stop) = (389, 405) #165, 181)
    a.verticalLine( tile, asic, start, stop)
    (start, stop) = (422, 438) #198, 214)
    a.verticalLine( tile, asic, start, stop)
    (start, stop) = (324, 326) #100, 102)
    a.horizontalLine( tile, asic, start, stop)
    (start, stop) = (468, 470) #244, 246)
    a.horizontalLine( tile, asic, start, stop)
    







#    if False: #True = "XFEL SUPE"    False = "R KLASSE !"
#        # Draw F
#        asic = 6
#        a.insertComment( "Letter F")
#        (start, stop) = (466, 476)
#        a.horizontalLine( 0, asic, start, stop)
#        (start, stop) = (34, 466)
#        a.verticalLine( 0, asic, start, stop)
#        (start, stop) = (258, 264)
#        a.horizontalLine( 0, asic, start, stop)
#        
#        # Draw E
#        asic=5
#        a.insertComment( "Letter E")
#        (start, stop) = (34, 45)
#        a.horizontalLine( 0, asic, start, stop)
#        (start, stop) = (466, 476)
#        a.horizontalLine( 0, asic, start, stop)
#        (start, stop) = (258, 263)
#        a.horizontalLine( 0, asic, start, stop)
#        (start, stop) = (34, 466)
#        a.verticalLine( 0, asic, start, stop)
#        
#        # Draw L
#        asic=4
#        a.insertComment( "Letter L")
#        (start, stop) = (34, 45)
#        a.horizontalLine( 0, asic, start, stop)
#        (start, stop) = (34, 466)
#        a.verticalLine( 0, asic, start, stop)
#
#        # Draw S
#        asic=3
#        a.insertComment( "Letter S")
#        (start, stop) = (34, 45)
#        a.horizontalLine( 0, asic, start, stop)
#        a.singlePixel(pixel=61, tile=0, asic=asic)
#    
#        (start, stop) = (77, 237)
#        a.verticalLine( 0, asic, start, stop)
#        a.singlePixel(pixel=252, tile=0, asic=asic)
#    
#        (start, stop) = (260, 267)
#        a.horizontalLine( 0, asic, start, stop)
#        a.singlePixel(pixel=275, tile=0, asic=asic)
#    
#        (start, stop) = (290, 434)
#        a.verticalLine( 0, asic, start, stop)
#        a.singlePixel(pixel=451, tile=0, asic=asic)
#        
#        (start, stop) = (468, 476)
#        a.horizontalLine( 0, asic, start, stop)
#    
#        # Draw U
#        asic=2
#        a.insertComment( "Letter U")
#        a.singlePixel(pixel=51, tile=0, asic=asic)
#        (start, stop) = (36, 44)
#        a.horizontalLine( 0, asic, start, stop)
#        a.singlePixel(pixel=61, tile=0, asic=asic)
#    
#        (start, stop) = (66, 466)
#        a.verticalLine( 0, asic, start, stop)
#    
#        (start, stop) = (78, 478)
#        a.verticalLine( 0, asic, start, stop)
#
#        # Draw P
#        asic=1
#        a.insertComment( "Letter P")
#        (start, stop) = (466, 474)
#        a.horizontalLine( 0, asic, start, stop)
#        a.singlePixel(pixel=459, tile=0, asic=asic)
#        (start, stop) = (300, 444)
#        a.verticalLine( 0, asic, start, stop)
#    
#        a.singlePixel(pixel=283, tile=0, asic=asic)
#        (start, stop) = (258, 266)
#        a.horizontalLine( 0, asic, start, stop)
#        
#        (start, stop) = (34, 466)
#        a.verticalLine( 0, asic, start, stop)
#        
#        # Draw E
#        asic=0
#        a.insertComment( "Letter E")
#        (start, stop) = (34, 45)
#        a.horizontalLine( 0, asic, start, stop)
#        (start, stop) = (466, 476)
#        a.horizontalLine( 0, asic, start, stop)
#        (start, stop) = (258, 263)
#        a.horizontalLine( 0, asic, start, stop)
#        (start, stop) = (34, 466)
#        a.verticalLine( 0, asic, start, stop)
#    
#    else:
#
#        # Draw R
#        asic=7
#        a.insertComment( "Letter R")
#        (start, stop) = (466, 474)
#        a.horizontalLine( 0, asic, start, stop)
#        a.singlePixel(pixel=459, tile=0, asic=asic)
#        (start, stop) = (300, 444)
#        a.verticalLine( 0, asic, start, stop)
#
#        a.singlePixel(pixel=283, tile=0, asic=asic)
#        (start, stop) = (258, 266)
#        a.horizontalLine( 0, asic, start, stop)
#        
#        (start, stop) = (34, 466)
#        a.verticalLine( 0, asic, start, stop)
#
#        a.singlePixel(pixel=46, tile=0, asic=asic)
#        a.singlePixel(pixel=62, tile=0, asic=asic)
#        a.singlePixel(pixel=77, tile=0, asic=asic)
#        a.singlePixel(pixel=93, tile=0, asic=asic)
#        a.singlePixel(pixel=109, tile=0, asic=asic)
#        a.singlePixel(pixel=108, tile=0, asic=asic)
#        a.singlePixel(pixel=124, tile=0, asic=asic)
#        a.singlePixel(pixel=140, tile=0, asic=asic)
#        a.singlePixel(pixel=139, tile=0, asic=asic)
#        a.singlePixel(pixel=155, tile=0, asic=asic)
#        a.singlePixel(pixel=171, tile=0, asic=asic)
#        a.singlePixel(pixel=170, tile=0, asic=asic)
#        a.singlePixel(pixel=186, tile=0, asic=asic)
#        a.singlePixel(pixel=202, tile=0, asic=asic)
#        a.singlePixel(pixel=201, tile=0, asic=asic)
#        a.singlePixel(pixel=217, tile=0, asic=asic)
#        a.singlePixel(pixel=233, tile=0, asic=asic)
#        a.singlePixel(pixel=249, tile=0, asic=asic)
#
#
#        # Draw K
#        asic=6
#        a.insertComment( "Letter K")
#        (start, stop) = (258, 264)
#        a.horizontalLine( 0, asic, start, stop)
#        
#        (start, stop) = (34, 466)
#        a.verticalLine( 0, asic, start, stop)
#
#        a.singlePixel(pixel=46, tile=0, asic=asic)
#        a.singlePixel(pixel=62, tile=0, asic=asic)
#        a.singlePixel(pixel=77, tile=0, asic=asic)
#        a.singlePixel(pixel=93, tile=0, asic=asic)
#        a.singlePixel(pixel=109, tile=0, asic=asic)
#        a.singlePixel(pixel=108, tile=0, asic=asic)
#        a.singlePixel(pixel=124, tile=0, asic=asic)
#        a.singlePixel(pixel=140, tile=0, asic=asic)
#        a.singlePixel(pixel=139, tile=0, asic=asic)
#        a.singlePixel(pixel=155, tile=0, asic=asic)
#        a.singlePixel(pixel=171, tile=0, asic=asic)
#        a.singlePixel(pixel=170, tile=0, asic=asic)
#        a.singlePixel(pixel=186, tile=0, asic=asic)
#        a.singlePixel(pixel=202, tile=0, asic=asic)
#        a.singlePixel(pixel=201, tile=0, asic=asic)
#        a.singlePixel(pixel=217, tile=0, asic=asic)
#        a.singlePixel(pixel=233, tile=0, asic=asic)
#
#        a.singlePixel(pixel=478, tile=0, asic=asic)
#        a.singlePixel(pixel=462, tile=0, asic=asic)
#        a.singlePixel(pixel=445, tile=0, asic=asic)
#        a.singlePixel(pixel=429, tile=0, asic=asic)
#        a.singlePixel(pixel=413, tile=0, asic=asic)
#        a.singlePixel(pixel=396, tile=0, asic=asic)
#        a.singlePixel(pixel=380, tile=0, asic=asic)
#        a.singlePixel(pixel=363, tile=0, asic=asic)
#        a.singlePixel(pixel=347, tile=0, asic=asic)
#        a.singlePixel(pixel=330, tile=0, asic=asic)
#        a.singlePixel(pixel=314, tile=0, asic=asic)
#        a.singlePixel(pixel=298, tile=0, asic=asic)
#        a.singlePixel(pixel=281, tile=0, asic=asic)
#        a.singlePixel(pixel=265, tile=0, asic=asic)
#        a.singlePixel(pixel=249, tile=0, asic=asic)
#
#        # Draw L
#        asic=5
#        a.insertComment( "Letter L")
#        (start, stop) = (34, 45)
#        a.horizontalLine( 0, asic, start, stop)
#        (start, stop) = (34, 466)
#        a.verticalLine( 0, asic, start, stop)
#
#        # Draw A
#        asic=4
#        a.insertComment( "Letter A")
#        a.singlePixel(pixel=34, tile=0, asic=asic)
#        a.singlePixel(pixel=45, tile=0, asic=asic)
#        (start, stop) = (51, 147)
#        a.verticalLine( 0, asic, start, stop)
#        (start, stop) = (164, 260)
#        a.verticalLine( 0, asic, start, stop)
#        (start, stop) = (277, 373)
#        a.verticalLine( 0, asic, start, stop)
#        (start, stop) = (390, 454)
#        a.verticalLine( 0, asic, start, stop)
#
#        (start, stop) = (471, 472)
#        a.horizontalLine( 0, asic, start, stop)
#        (start, stop) = (262, 265)
#        a.horizontalLine( 0, asic, start, stop)
#
#        (start, stop) = (60, 156)
#        a.verticalLine( 0, asic, start, stop)
#        (start, stop) = (171, 267)
#        a.verticalLine( 0, asic, start, stop)
#        (start, stop) = (282, 378)
#        a.verticalLine( 0, asic, start, stop)
#        (start, stop) = (393, 457)
#        a.verticalLine( 0, asic, start, stop)
#
#        # Draw S
#        asic=3
#        a.insertComment( "Letter S")
#        (start, stop) = (34, 44)
#        a.horizontalLine( 0, asic, start, stop)
#        a.singlePixel(pixel=61, tile=0, asic=asic)
#    
#        (start, stop) = (77, 237)
#        a.verticalLine( 0, asic, start, stop)
#        a.singlePixel(pixel=252, tile=0, asic=asic)
#    
#        (start, stop) = (260, 267)
#        a.horizontalLine( 0, asic, start, stop)
#        a.singlePixel(pixel=275, tile=0, asic=asic)
#    
#        (start, stop) = (290, 434)
#        a.verticalLine( 0, asic, start, stop)
#        a.singlePixel(pixel=451, tile=0, asic=asic)
#        
#        (start, stop) = (468, 476)
#        a.horizontalLine( 0, asic, start, stop)
#
#        # Draw S
#        asic=2
#        a.insertComment( "Letter S")
#        (start, stop) = (34, 44)
#        a.horizontalLine( 0, asic, start, stop)
#        a.singlePixel(pixel=61, tile=0, asic=asic)
#    
#        (start, stop) = (77, 237)
#        a.verticalLine( 0, asic, start, stop)
#        a.singlePixel(pixel=252, tile=0, asic=asic)
#    
#        (start, stop) = (260, 267)
#        a.horizontalLine( 0, asic, start, stop)
#        a.singlePixel(pixel=275, tile=0, asic=asic)
#    
#        (start, stop) = (290, 434)
#        a.verticalLine( 0, asic, start, stop)
#        a.singlePixel(pixel=451, tile=0, asic=asic)
#        
#        (start, stop) = (468, 476)
#        a.horizontalLine( 0, asic, start, stop)
#
#        # Draw E
#        asic=1
#        a.insertComment( "Letter E")
#        (start, stop) = (34, 45)
#        a.horizontalLine( 0, asic, start, stop)
#        (start, stop) = (466, 476)
#        a.horizontalLine( 0, asic, start, stop)
#        (start, stop) = (258, 263)
#        a.horizontalLine( 0, asic, start, stop)
#        (start, stop) = (34, 466)
#        a.verticalLine( 0, asic, start, stop)
#        
#
#        # Draw "!"
#        asic=0
#        a.insertComment( "Letter '!'")
#        (start, stop) = (104, 472)
#        a.verticalLine( 0, asic, start, stop)
#        (start, stop) = (105, 473)
#        a.verticalLine( 0, asic, start, stop)
#
#        a.singlePixel(pixel=40, tile=0, asic=asic)
#        a.singlePixel(pixel=41, tile=0, asic=asic)
#        a.singlePixel(pixel=57, tile=0, asic=asic)
#        a.singlePixel(pixel=56, tile=0, asic=asic)
