#!/bin/bash

#      RHS Power Card (Two Tile System)

python LpdPowerControl.py --asicmodule 2 --hvbias 50
python LpdPowerControl.py --asicmodule 2 --lv 1 --hv 1

echo "-=-=-=-=-=-=-=-=-=- 2-TILE SYSTEM: POWER CARDS' INFO: -=-=-=-=-=-=-=-=-=-"

python LpdPowerStatus.py
