#!/bin/bash

#      RHS Power Card (Two Tile System)

python LpdPowerControl.py --hvbias 50 --femI2cBus 512
python LpdPowerControl.py --lv 1 --hv 1 --femI2cBus 512

echo "-=-=-=-=-=-=-=-=-=-=-=-=-         POWER CARDS' INFO:         -=-=-=-=-=-=-=-=-=-=-=-=-"

python LpdPowerStatus.py
