#!/bin/bash
#
#

#      RHS Power Card

python LpdI2cTest.py --hvbias 50 --femI2cBus 512
python LpdI2cTest.py --lv 1 --hv 1 --femI2cBus 512

#      LHS Power Card

python LpdI2cTest.py --hvbias 50 --femI2cBus 768
python LpdI2cTest.py --lv 1 --hv 1 --femI2cBus 768


#echo "Running fem_asic_test.py 20 times.."
#echo "1 of 20"
#python LpdFemTests/fem_asic_test.py

echo "-=-=-=-=-=-=-=-=-=-=-=-=-         POWER CARDS' INFO:         -=-=-=-=-=-=-=-=-=-=-=-=-"

python LpdPowerCardTest.py 0x200
python LpdPowerCardTest.py 0x300