#!/bin/bash

#      RHS Power Card

python LpdPowerControl.py --hvbias 50
python LpdPowerControl.py --lv 1 --hv 1

#      LHS Power Card

python LpdPowerControl.py --hvbias 50
python LpdPowerControl.py --lv 1 --hv 1

echo "-=-=-=-=-=-=-=-=-=-=-=-=-         POWER CARDS' INFO:         -=-=-=-=-=-=-=-=-=-=-=-=-"

python LpdSuperModulePowerStatus.py