#!/bin/bash
#
#	Run fem_asic_test.py repeatedly
#

for ((  i = 0 ;  i <= 50;  i++  ))
do
  echo "-=-=-=-=-=-=-=-=-=-=-=-=- Executing time no: $i -=-=-=-=-=-=-=-=-=-=-=-=-"
  python fem_asic_test.py
done

#echo "Running fem_asic_test.py 20 times.."
#echo "1 of 20"
#python LpdFemTests/fem_asic_test.py

echo "-=-=-=-=-=-=-=-=-=-=-=-=-         Done!         -=-=-=-=-=-=-=-=-=-=-=-=-"
