#!/bin/bash

#      FEM0 - 192.168.2.101

echo "~+~+~ Connecting to host: 192.168.2.101, port: 6969, asicmodule:  supermodule  ~+~+~"
python power_control.py --femhost 192.168.2.101 --femport 6969 --asicmodule 0 --hvbias 50
python power_control.py --femhost 192.168.2.101 --femport 6969 --asicmodule 0 --lv 1 --hv 1

echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"

#      FEM1 - 192.168.2.102

echo "~+~+~ Connecting to host: 192.168.2.102, port: 6969, asicmodule:  supermodule  ~+~+~"
python power_control.py --femhost 192.168.2.102 --femport 6969 --asicmodule 0 --hvbias 50
python power_control.py --femhost 192.168.2.102 --femport 6969 --asicmodule 0 --lv 1 --hv 1

echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"

#      FEM1 - 192.168.2.103

echo "~+~+~ Connecting to host: 192.168.2.103, port: 6969, asicmodule:  supermodule  ~+~+~"
python power_control.py --femhost 192.168.2.103 --femport 6969 --asicmodule 0 --hvbias 50
python power_control.py --femhost 192.168.2.103 --femport 6969 --asicmodule 0 --lv 1 --hv 1

echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"

#      FEM1 - 192.168.2.104

echo "~+~+~ Connecting to host: 192.168.2.104, port: 6969, asicmodule:  supermodule  ~+~+~"
python power_control.py --femhost 192.168.2.104 --femport 6969 --asicmodule 0 --hvbias 50
python power_control.py --femhost 192.168.2.104 --femport 6969 --asicmodule 0 --lv 1 --hv 1


echo "-=-=-=-=-=-=-=-=-=- QUADRANT DETECTOR: POWER CARDS' INFO: -=-=-=-=-=-=-=-=-=-"

python super_module_power_status.py --femhost 192.168.2.101 --femport 6969
python super_module_power_status.py --femhost 192.168.2.102 --femport 6969
python super_module_power_status.py --femhost 192.168.2.103 --femport 6969
python super_module_power_status.py --femhost 192.168.2.104 --femport 6969
