#!/bin/bash

echo "~+~+~ Connecting to host: 192.168.2.2, port: 6969, asicmodule:  supermodule  ~+~+~"
python power_control.py --femhost 192.168.2.2 --femport 6969 --asicmodule 0 --hvbias 50

echo "~+~+~ Connecting to host: 192.168.2.2, port: 6969, asicmodule:  supermodule  ~+~+~"
python power_control.py --femhost 192.168.2.2 --femport 6969 --asicmodule 0 --lv 1 --hv 1

echo "-=-=-=-=-=-=-=-=-=- SUPERMODULE: POWER CARDS' INFO: -=-=-=-=-=-=-=-=-=-"
python super_module_power_status.py --femhost 192.168.2.2 --femport 6969
