#!/bin/sh

export LPD_FEM_SW_PATH=/u/ckd27546/workspace/lpdSoftware/
export LPD_FEM_GUI_PATH=$LPD_FEM_SW_PATH/LpdFemTests

export PYTHONPATH=$LPD_FEM_SW_PATH/LpdFemGui:$LPD_FEM_SW_PATH:${PYTHONPATH:-}
export LPD_FEM_GUI_CONFIG_PATH=$LPD_FEM_GUI_PATH/ConfigFiles

python $LPD_FEM_GUI_PATH/LpdDataDisplay.py -style gtk

