# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LpdDataDisplayMainWindow.ui'
#
# Created: Mon Jun 10 13:25:10 2013
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(799, 792)
        MainWindow.setStatusTip(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalTabWidget = QtGui.QTabWidget(self.centralwidget)
        self.verticalTabWidget.setGeometry(QtCore.QRect(10, 60, 781, 681))
        self.verticalTabWidget.setObjectName(_fromUtf8("verticalTabWidget"))
        self.daqTab = QtGui.QWidget()
        self.daqTab.setObjectName(_fromUtf8("daqTab"))
        self.setupGroupBox = QtGui.QGroupBox(self.daqTab)
        self.setupGroupBox.setGeometry(QtCore.QRect(10, 100, 761, 191))
        self.setupGroupBox.setObjectName(_fromUtf8("setupGroupBox"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.setupGroupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 783, 171))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(6, -1, 6, -1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setMargin(0)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.fastParamEdit = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.fastParamEdit.setReadOnly(True)
        self.fastParamEdit.setObjectName(_fromUtf8("fastParamEdit"))
        self.gridLayout.addWidget(self.fastParamEdit, 2, 1, 1, 1)
        self.fastParamLabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fastParamLabel.sizePolicy().hasHeightForWidth())
        self.fastParamLabel.setSizePolicy(sizePolicy)
        self.fastParamLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.fastParamLabel.setObjectName(_fromUtf8("fastParamLabel"))
        self.gridLayout.addWidget(self.fastParamLabel, 2, 0, 1, 1)
        self.slowParamEdit = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.slowParamEdit.setReadOnly(True)
        self.slowParamEdit.setObjectName(_fromUtf8("slowParamEdit"))
        self.gridLayout.addWidget(self.slowParamEdit, 1, 1, 1, 1)
        self.slowParamLabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slowParamLabel.sizePolicy().hasHeightForWidth())
        self.slowParamLabel.setSizePolicy(sizePolicy)
        self.slowParamLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.slowParamLabel.setObjectName(_fromUtf8("slowParamLabel"))
        self.gridLayout.addWidget(self.slowParamLabel, 1, 0, 1, 1)
        self.fastParamBtn = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.fastParamBtn.setObjectName(_fromUtf8("fastParamBtn"))
        self.gridLayout.addWidget(self.fastParamBtn, 2, 2, 1, 1)
        self.dataPathEdit = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.dataPathEdit.setReadOnly(True)
        self.dataPathEdit.setObjectName(_fromUtf8("dataPathEdit"))
        self.gridLayout.addWidget(self.dataPathEdit, 3, 1, 1, 1)
        self.dataPathBtn = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.dataPathBtn.setObjectName(_fromUtf8("dataPathBtn"))
        self.gridLayout.addWidget(self.dataPathBtn, 3, 2, 1, 1)
        self.readoutParamBtn = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.readoutParamBtn.setObjectName(_fromUtf8("readoutParamBtn"))
        self.gridLayout.addWidget(self.readoutParamBtn, 0, 2, 1, 1)
        self.slowParamBtn = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.slowParamBtn.setObjectName(_fromUtf8("slowParamBtn"))
        self.gridLayout.addWidget(self.slowParamBtn, 1, 2, 1, 1)
        self.readoutParamLabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.readoutParamLabel.sizePolicy().hasHeightForWidth())
        self.readoutParamLabel.setSizePolicy(sizePolicy)
        self.readoutParamLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.readoutParamLabel.setObjectName(_fromUtf8("readoutParamLabel"))
        self.gridLayout.addWidget(self.readoutParamLabel, 0, 0, 1, 1)
        self.readoutParamEdit = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.readoutParamEdit.setReadOnly(True)
        self.readoutParamEdit.setObjectName(_fromUtf8("readoutParamEdit"))
        self.gridLayout.addWidget(self.readoutParamEdit, 0, 1, 1, 1)
        self.dataPathLabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataPathLabel.sizePolicy().hasHeightForWidth())
        self.dataPathLabel.setSizePolicy(sizePolicy)
        self.dataPathLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.dataPathLabel.setObjectName(_fromUtf8("dataPathLabel"))
        self.gridLayout.addWidget(self.dataPathLabel, 3, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.gainModeAutoSel = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.gainModeAutoSel.setObjectName(_fromUtf8("gainModeAutoSel"))
        self.gainOverrideButtonGroup = QtGui.QButtonGroup(MainWindow)
        self.gainOverrideButtonGroup.setObjectName(_fromUtf8("gainOverrideButtonGroup"))
        self.gainOverrideButtonGroup.addButton(self.gainModeAutoSel)
        self.gridLayout_12.addWidget(self.gainModeAutoSel, 1, 12, 1, 1)
        self.pixelFbk5Sel = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.pixelFbk5Sel.setObjectName(_fromUtf8("pixelFbk5Sel"))
        self.pixelFbkButtonGroup = QtGui.QButtonGroup(MainWindow)
        self.pixelFbkButtonGroup.setObjectName(_fromUtf8("pixelFbkButtonGroup"))
        self.pixelFbkButtonGroup.addButton(self.pixelFbk5Sel)
        self.gridLayout_12.addWidget(self.pixelFbk5Sel, 1, 8, 1, 1)
        self.label_82 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.gridLayout_12.addWidget(self.label_82, 1, 11, 1, 1)
        self.label_30 = QtGui.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setMinimumSize(QtCore.QSize(0, 0))
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_12.addWidget(self.label_30, 1, 7, 1, 1)
        self.triggerDelayEdit = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.triggerDelayEdit.sizePolicy().hasHeightForWidth())
        self.triggerDelayEdit.setSizePolicy(sizePolicy)
        self.triggerDelayEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.triggerDelayEdit.setObjectName(_fromUtf8("triggerDelayEdit"))
        self.gridLayout_12.addWidget(self.triggerDelayEdit, 1, 5, 1, 1)
        self.externalTriggerSel = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.externalTriggerSel.setText(_fromUtf8(""))
        self.externalTriggerSel.setChecked(False)
        self.externalTriggerSel.setTristate(False)
        self.externalTriggerSel.setObjectName(_fromUtf8("externalTriggerSel"))
        self.gridLayout_12.addWidget(self.externalTriggerSel, 1, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem, 2, 2, 1, 1)
        self.label_27 = QtGui.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_12.addWidget(self.label_27, 1, 4, 1, 1)
        self.label_29 = QtGui.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_12.addWidget(self.label_29, 1, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_12.addWidget(self.label_24, 1, 2, 1, 1)
        self.numTrainsEdit = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numTrainsEdit.sizePolicy().hasHeightForWidth())
        self.numTrainsEdit.setSizePolicy(sizePolicy)
        self.numTrainsEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.numTrainsEdit.setObjectName(_fromUtf8("numTrainsEdit"))
        self.gridLayout_12.addWidget(self.numTrainsEdit, 1, 1, 1, 1)
        self.gainModex100Sel = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.gainModex100Sel.setObjectName(_fromUtf8("gainModex100Sel"))
        self.gainOverrideButtonGroup.addButton(self.gainModex100Sel)
        self.gridLayout_12.addWidget(self.gainModex100Sel, 1, 15, 1, 1)
        self.gainModex1Sel = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.gainModex1Sel.setObjectName(_fromUtf8("gainModex1Sel"))
        self.gainOverrideButtonGroup.addButton(self.gainModex1Sel)
        self.gridLayout_12.addWidget(self.gainModex1Sel, 1, 13, 1, 1)
        self.gainModex10Sel = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.gainModex10Sel.setObjectName(_fromUtf8("gainModex10Sel"))
        self.gainOverrideButtonGroup.addButton(self.gainModex10Sel)
        self.gridLayout_12.addWidget(self.gainModex10Sel, 1, 14, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem1, 1, 16, 1, 1)
        self.pixelFbk50Sel = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.pixelFbk50Sel.setObjectName(_fromUtf8("pixelFbk50Sel"))
        self.pixelFbkButtonGroup.addButton(self.pixelFbk50Sel)
        self.gridLayout_12.addWidget(self.pixelFbk50Sel, 1, 9, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem2, 1, 10, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem3, 1, 6, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_12)
        self.operateGroupBox = QtGui.QGroupBox(self.daqTab)
        self.operateGroupBox.setEnabled(False)
        self.operateGroupBox.setGeometry(QtCore.QRect(10, 10, 371, 91))
        self.operateGroupBox.setObjectName(_fromUtf8("operateGroupBox"))
        self.verticalLayoutWidget = QtGui.QWidget(self.operateGroupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 20, 413, 71))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.operateBtnBox = QtGui.QGridLayout()
        self.operateBtnBox.setContentsMargins(20, -1, 20, -1)
        self.operateBtnBox.setHorizontalSpacing(40)
        self.operateBtnBox.setVerticalSpacing(2)
        self.operateBtnBox.setObjectName(_fromUtf8("operateBtnBox"))
        self.stopBtn = QtGui.QPushButton(self.verticalLayoutWidget)
        self.stopBtn.setObjectName(_fromUtf8("stopBtn"))
        self.operateBtnBox.addWidget(self.stopBtn, 0, 2, 1, 1)
        self.configBtn = QtGui.QPushButton(self.verticalLayoutWidget)
        self.configBtn.setObjectName(_fromUtf8("configBtn"))
        self.operateBtnBox.addWidget(self.configBtn, 0, 0, 1, 1)
        self.runBtn = QtGui.QPushButton(self.verticalLayoutWidget)
        self.runBtn.setObjectName(_fromUtf8("runBtn"))
        self.operateBtnBox.addWidget(self.runBtn, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.operateBtnBox)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem4)
        self.label_37 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.horizontalLayout_13.addWidget(self.label_37)
        self.fileWriteSel = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.fileWriteSel.setText(_fromUtf8(""))
        self.fileWriteSel.setObjectName(_fromUtf8("fileWriteSel"))
        self.horizontalLayout_13.addWidget(self.fileWriteSel)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem5)
        self.label_70 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_70.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.horizontalLayout_13.addWidget(self.label_70)
        self.liveViewSel = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.liveViewSel.setText(_fromUtf8(""))
        self.liveViewSel.setObjectName(_fromUtf8("liveViewSel"))
        self.horizontalLayout_13.addWidget(self.liveViewSel)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem6)
        self.label_71 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_71.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.horizontalLayout_13.addWidget(self.label_71)
        self.liveViewDivisorEdit = QtGui.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.liveViewDivisorEdit.sizePolicy().hasHeightForWidth())
        self.liveViewDivisorEdit.setSizePolicy(sizePolicy)
        self.liveViewDivisorEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.liveViewDivisorEdit.setObjectName(_fromUtf8("liveViewDivisorEdit"))
        self.horizontalLayout_13.addWidget(self.liveViewDivisorEdit)
        self.label_74 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.horizontalLayout_13.addWidget(self.label_74)
        self.liveViewOffsetEdit = QtGui.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.liveViewOffsetEdit.sizePolicy().hasHeightForWidth())
        self.liveViewOffsetEdit.setSizePolicy(sizePolicy)
        self.liveViewOffsetEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.liveViewOffsetEdit.setObjectName(_fromUtf8("liveViewOffsetEdit"))
        self.horizontalLayout_13.addWidget(self.liveViewOffsetEdit)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.messageGroupBox = QtGui.QGroupBox(self.daqTab)
        self.messageGroupBox.setGeometry(QtCore.QRect(10, 290, 761, 361))
        self.messageGroupBox.setObjectName(_fromUtf8("messageGroupBox"))
        self.messageBox = QtGui.QPlainTextEdit(self.messageGroupBox)
        self.messageBox.setGeometry(QtCore.QRect(0, 20, 761, 331))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MiscFixed"))
        font.setPointSize(10)
        self.messageBox.setFont(font)
        self.messageBox.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.messageBox.setReadOnly(True)
        self.messageBox.setObjectName(_fromUtf8("messageBox"))
        self.runGroupBox = QtGui.QGroupBox(self.daqTab)
        self.runGroupBox.setEnabled(True)
        self.runGroupBox.setGeometry(QtCore.QRect(390, 10, 381, 91))
        self.runGroupBox.setObjectName(_fromUtf8("runGroupBox"))
        self.gridLayoutWidget_5 = QtGui.QWidget(self.runGroupBox)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(0, 20, 381, 71))
        self.gridLayoutWidget_5.setObjectName(_fromUtf8("gridLayoutWidget_5"))
        self.gridLayout_6 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setVerticalSpacing(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_28 = QtGui.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setMinimumSize(QtCore.QSize(80, 0))
        self.label_28.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_6.addWidget(self.label_28, 0, 0, 1, 1)
        self.runNumber = QtGui.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runNumber.sizePolicy().hasHeightForWidth())
        self.runNumber.setSizePolicy(sizePolicy)
        self.runNumber.setMinimumSize(QtCore.QSize(0, 0))
        self.runNumber.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.runNumber.setFont(font)
        self.runNumber.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.runNumber.setObjectName(_fromUtf8("runNumber"))
        self.gridLayout_6.addWidget(self.runNumber, 0, 1, 1, 1)
        self.label_72 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_72.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.gridLayout_6.addWidget(self.label_72, 1, 0, 1, 1)
        self.runState = QtGui.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runState.sizePolicy().hasHeightForWidth())
        self.runState.setSizePolicy(sizePolicy)
        self.runState.setMinimumSize(QtCore.QSize(80, 0))
        self.runState.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.runState.setFont(font)
        self.runState.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.runState.setObjectName(_fromUtf8("runState"))
        self.gridLayout_6.addWidget(self.runState, 0, 3, 1, 1)
        self.frameRx = QtGui.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameRx.sizePolicy().hasHeightForWidth())
        self.frameRx.setSizePolicy(sizePolicy)
        self.frameRx.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.frameRx.setFont(font)
        self.frameRx.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.frameRx.setIndent(-1)
        self.frameRx.setObjectName(_fromUtf8("frameRx"))
        self.gridLayout_6.addWidget(self.frameRx, 1, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMinimumSize(QtCore.QSize(0, 0))
        self.label_26.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_6.addWidget(self.label_26, 0, 2, 1, 1)
        self.imageProc = QtGui.QLabel(self.gridLayoutWidget_5)
        self.imageProc.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.imageProc.setFont(font)
        self.imageProc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.imageProc.setIndent(-1)
        self.imageProc.setObjectName(_fromUtf8("imageProc"))
        self.gridLayout_6.addWidget(self.imageProc, 2, 3, 1, 1)
        self.label_76 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_76.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_76.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.gridLayout_6.addWidget(self.label_76, 2, 2, 1, 1)
        self.label_73 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_73.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.gridLayout_6.addWidget(self.label_73, 2, 0, 1, 1)
        self.frameProc = QtGui.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameProc.sizePolicy().hasHeightForWidth())
        self.frameProc.setSizePolicy(sizePolicy)
        self.frameProc.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.frameProc.setFont(font)
        self.frameProc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.frameProc.setIndent(-1)
        self.frameProc.setObjectName(_fromUtf8("frameProc"))
        self.gridLayout_6.addWidget(self.frameProc, 2, 1, 1, 1)
        self.dataRx = QtGui.QLabel(self.gridLayoutWidget_5)
        self.dataRx.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.dataRx.setFont(font)
        self.dataRx.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dataRx.setIndent(-1)
        self.dataRx.setObjectName(_fromUtf8("dataRx"))
        self.gridLayout_6.addWidget(self.dataRx, 1, 3, 1, 1)
        self.label_75 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_75.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_75.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.gridLayout_6.addWidget(self.label_75, 1, 2, 1, 1)
        self.verticalTabWidget.addTab(self.daqTab, _fromUtf8(""))
        self.pwrTab = QtGui.QWidget()
        self.pwrTab.setObjectName(_fromUtf8("pwrTab"))
        self.verticalTabWidget.addTab(self.pwrTab, _fromUtf8(""))
        self.configTab = QtGui.QWidget()
        self.configTab.setObjectName(_fromUtf8("configTab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.configTab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem8 = QtGui.QSpacerItem(20, 130, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.verticalTabWidget.addTab(self.configTab, _fromUtf8(""))
        self.evrTab = QtGui.QWidget()
        self.evrTab.setObjectName(_fromUtf8("evrTab"))
        self.verticalTabWidget.addTab(self.evrTab, _fromUtf8(""))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 0, 781, 52))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.horizontalLayoutWidget_2)
        self.groupBox.setEnabled(True)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 381, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.connectLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.connectLayout.setContentsMargins(6, -1, 6, -1)
        self.connectLayout.setObjectName(_fromUtf8("connectLayout"))
        self.label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.connectLayout.addWidget(self.label)
        self.connectAddr = QtGui.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectAddr.sizePolicy().hasHeightForWidth())
        self.connectAddr.setSizePolicy(sizePolicy)
        self.connectAddr.setMinimumSize(QtCore.QSize(90, 0))
        self.connectAddr.setMaximumSize(QtCore.QSize(140, 16777215))
        self.connectAddr.setText(_fromUtf8(""))
        self.connectAddr.setMaxLength(200)
        self.connectAddr.setFrame(True)
        self.connectAddr.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.connectAddr.setProperty("placeholderText", _fromUtf8(""))
        self.connectAddr.setObjectName(_fromUtf8("connectAddr"))
        self.connectLayout.addWidget(self.connectAddr)
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.connectLayout.addWidget(self.label_2)
        self.connectPort = QtGui.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectPort.sizePolicy().hasHeightForWidth())
        self.connectPort.setSizePolicy(sizePolicy)
        self.connectPort.setMaximumSize(QtCore.QSize(60, 16777215))
        self.connectPort.setText(_fromUtf8(""))
        self.connectPort.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.connectPort.setProperty("placeholderText", _fromUtf8(""))
        self.connectPort.setObjectName(_fromUtf8("connectPort"))
        self.connectLayout.addWidget(self.connectPort)
        self.connectButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.connectButton.setObjectName(_fromUtf8("connectButton"))
        self.connectLayout.addWidget(self.connectButton)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.horizontalLayoutWidget_2)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 10, 391, 41))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(6, 0, 6, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_22 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_4.addWidget(self.label_22)
        self.connectStatus = QtGui.QLabel(self.horizontalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectStatus.sizePolicy().hasHeightForWidth())
        self.connectStatus.setSizePolicy(sizePolicy)
        self.connectStatus.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.connectStatus.setFont(font)
        self.connectStatus.setObjectName(_fromUtf8("connectStatus"))
        self.horizontalLayout_4.addWidget(self.connectStatus)
        self.label_23 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_4.addWidget(self.label_23)
        self.lvStatus = QtGui.QLabel(self.horizontalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lvStatus.sizePolicy().hasHeightForWidth())
        self.lvStatus.setSizePolicy(sizePolicy)
        self.lvStatus.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lvStatus.setFont(font)
        self.lvStatus.setObjectName(_fromUtf8("lvStatus"))
        self.horizontalLayout_4.addWidget(self.lvStatus)
        self.label_25 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_4.addWidget(self.label_25)
        self.hvStatus = QtGui.QLabel(self.horizontalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hvStatus.sizePolicy().hasHeightForWidth())
        self.hvStatus.setSizePolicy(sizePolicy)
        self.hvStatus.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.hvStatus.setFont(font)
        self.hvStatus.setObjectName(_fromUtf8("hvStatus"))
        self.horizontalLayout_4.addWidget(self.hvStatus)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.verticalTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "STFC LPD Readout GUI", None, QtGui.QApplication.UnicodeUTF8))
        self.setupGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.fastParamLabel.setText(QtGui.QApplication.translate("MainWindow", "Fast Cmd Seq:", None, QtGui.QApplication.UnicodeUTF8))
        self.slowParamLabel.setText(QtGui.QApplication.translate("MainWindow", "Slow Params:", None, QtGui.QApplication.UnicodeUTF8))
        self.fastParamBtn.setText(QtGui.QApplication.translate("MainWindow", "Select...", None, QtGui.QApplication.UnicodeUTF8))
        self.dataPathBtn.setText(QtGui.QApplication.translate("MainWindow", "Select...", None, QtGui.QApplication.UnicodeUTF8))
        self.readoutParamBtn.setText(QtGui.QApplication.translate("MainWindow", "Select...", None, QtGui.QApplication.UnicodeUTF8))
        self.slowParamBtn.setText(QtGui.QApplication.translate("MainWindow", "Select...", None, QtGui.QApplication.UnicodeUTF8))
        self.readoutParamLabel.setText(QtGui.QApplication.translate("MainWindow", "Readout Params:", None, QtGui.QApplication.UnicodeUTF8))
        self.dataPathLabel.setText(QtGui.QApplication.translate("MainWindow", "Data File Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.gainModeAutoSel.setText(QtGui.QApplication.translate("MainWindow", "Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.pixelFbk5Sel.setText(QtGui.QApplication.translate("MainWindow", "5pF", None, QtGui.QApplication.UnicodeUTF8))
        self.label_82.setText(QtGui.QApplication.translate("MainWindow", "Gain Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "Fbk:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Delay:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "Num Trains:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Ext Trigger:", None, QtGui.QApplication.UnicodeUTF8))
        self.gainModex100Sel.setText(QtGui.QApplication.translate("MainWindow", "x100", None, QtGui.QApplication.UnicodeUTF8))
        self.gainModex1Sel.setText(QtGui.QApplication.translate("MainWindow", "x1", None, QtGui.QApplication.UnicodeUTF8))
        self.gainModex10Sel.setText(QtGui.QApplication.translate("MainWindow", "x10", None, QtGui.QApplication.UnicodeUTF8))
        self.pixelFbk50Sel.setText(QtGui.QApplication.translate("MainWindow", "50pF", None, QtGui.QApplication.UnicodeUTF8))
        self.operateGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Operate", None, QtGui.QApplication.UnicodeUTF8))
        self.stopBtn.setText(QtGui.QApplication.translate("MainWindow", "Abort", None, QtGui.QApplication.UnicodeUTF8))
        self.configBtn.setText(QtGui.QApplication.translate("MainWindow", "Configure", None, QtGui.QApplication.UnicodeUTF8))
        self.runBtn.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("MainWindow", "Write Files:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_70.setText(QtGui.QApplication.translate("MainWindow", "Live view:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_71.setText(QtGui.QApplication.translate("MainWindow", "Divisor:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_74.setText(QtGui.QApplication.translate("MainWindow", "Offset:", None, QtGui.QApplication.UnicodeUTF8))
        self.messageGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Messages", None, QtGui.QApplication.UnicodeUTF8))
        self.messageBox.setPlainText(QtGui.QApplication.translate("MainWindow", "Hi\n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.runGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Run Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "Run Number:", None, QtGui.QApplication.UnicodeUTF8))
        self.runNumber.setText(QtGui.QApplication.translate("MainWindow", "??", None, QtGui.QApplication.UnicodeUTF8))
        self.label_72.setText(QtGui.QApplication.translate("MainWindow", "Frame RX:", None, QtGui.QApplication.UnicodeUTF8))
        self.runState.setText(QtGui.QApplication.translate("MainWindow", "Configuring", None, QtGui.QApplication.UnicodeUTF8))
        self.frameRx.setText(QtGui.QApplication.translate("MainWindow", "??", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "State:", None, QtGui.QApplication.UnicodeUTF8))
        self.imageProc.setText(QtGui.QApplication.translate("MainWindow", "??", None, QtGui.QApplication.UnicodeUTF8))
        self.label_76.setText(QtGui.QApplication.translate("MainWindow", "Image Proc:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_73.setText(QtGui.QApplication.translate("MainWindow", "Frame Proc:", None, QtGui.QApplication.UnicodeUTF8))
        self.frameProc.setText(QtGui.QApplication.translate("MainWindow", "??", None, QtGui.QApplication.UnicodeUTF8))
        self.dataRx.setText(QtGui.QApplication.translate("MainWindow", "??", None, QtGui.QApplication.UnicodeUTF8))
        self.label_75.setText(QtGui.QApplication.translate("MainWindow", "Data Rx:", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalTabWidget.setTabText(self.verticalTabWidget.indexOf(self.daqTab), QtGui.QApplication.translate("MainWindow", "DAQ", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalTabWidget.setTabText(self.verticalTabWidget.indexOf(self.pwrTab), QtGui.QApplication.translate("MainWindow", "PWR", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalTabWidget.setTabText(self.verticalTabWidget.indexOf(self.configTab), QtGui.QApplication.translate("MainWindow", "FEM", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalTabWidget.setTabText(self.verticalTabWidget.indexOf(self.evrTab), QtGui.QApplication.translate("MainWindow", "EVR", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Address:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.connectButton.setText(QtGui.QApplication.translate("MainWindow", "  Connect  ", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Connected:", None, QtGui.QApplication.UnicodeUTF8))
        self.connectStatus.setText(QtGui.QApplication.translate("MainWindow", "NO", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "LV:", None, QtGui.QApplication.UnicodeUTF8))
        self.lvStatus.setText(QtGui.QApplication.translate("MainWindow", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "HV:", None, QtGui.QApplication.UnicodeUTF8))
        self.hvStatus.setText(QtGui.QApplication.translate("MainWindow", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))

