#!/bin/sh

export LPD_FEM_SW_PATH=/aeg_sw/work/projects/lpd/src/lpd-detector/app/lpd
export LPD_FEM_GUI_PATH=$LPD_FEM_SW_PATH/gui

#export PYTHONPATH=$LPD_FEM_SW_PATH/gui:$LPD_FEM_SW_PATH:${PYTHONPATH:-}
#export PYTHONPATH=/u/xfu59478/develop/projects/lpd/odin-data/tools/python:${PYTHONPATH:-}
export LPD_FEM_GUI_CONFIG_PATH=$LPD_FEM_GUI_PATH/config

python $LPD_FEM_GUI_PATH/gui.py -style gtk
