#!/bin/sh

export LPD_FEM_SW_PATH=/u/xfu59478/develop/projects/lpd/lpd-fem/python/src
export LPD_FEM_GUI_PATH=$LPD_FEM_SW_PATH/LpdFemGui

export PYTHONPATH=$LPD_FEM_SW_PATH/LpdFemGui:$LPD_FEM_SW_PATH:${PYTHONPATH:-}
export PYTHONPATH=/u/xfu59478/develop/projects/lpd/odin-data/tools/python:${PYTHONPATH:-}
export LPD_FEM_GUI_CONFIG_PATH=$LPD_FEM_GUI_PATH/config

python $LPD_FEM_GUI_PATH/LpdFemGui.py -style gtk

