# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/tcn45/workspace/excalibur/python/src/FemGui/FemGuiMainWindow.ui'
#
# Created: Fri Oct 21 09:18:48 2011
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 792)
        MainWindow.setStatusTip(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 781, 541))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setEnabled(True)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 779, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.connectLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.connectLayout.setContentsMargins(10, -1, -1, -1)
        self.connectLayout.setObjectName(_fromUtf8("connectLayout"))
        self.label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.connectLayout.addWidget(self.label)
        self.connectAddr = QtGui.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectAddr.sizePolicy().hasHeightForWidth())
        self.connectAddr.setSizePolicy(sizePolicy)
        self.connectAddr.setMaximumSize(QtCore.QSize(120, 16777215))
        self.connectAddr.setText(_fromUtf8(""))
        self.connectAddr.setMaxLength(200)
        self.connectAddr.setFrame(True)
        self.connectAddr.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.connectAddr.setPlaceholderText(_fromUtf8(""))
        self.connectAddr.setObjectName(_fromUtf8("connectAddr"))
        self.connectLayout.addWidget(self.connectAddr)
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.connectLayout.addWidget(self.label_2)
        self.connectPort = QtGui.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectPort.sizePolicy().hasHeightForWidth())
        self.connectPort.setSizePolicy(sizePolicy)
        self.connectPort.setMaximumSize(QtCore.QSize(80, 16777215))
        self.connectPort.setText(_fromUtf8(""))
        self.connectPort.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.connectPort.setPlaceholderText(_fromUtf8(""))
        self.connectPort.setObjectName(_fromUtf8("connectPort"))
        self.connectLayout.addWidget(self.connectPort)
        self.connectButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.connectButton.setObjectName(_fromUtf8("connectButton"))
        self.connectLayout.addWidget(self.connectButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.connectLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.groupBox)
        self.configGroupBox = QtGui.QGroupBox(self.verticalLayoutWidget)
        self.configGroupBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.configGroupBox.sizePolicy().hasHeightForWidth())
        self.configGroupBox.setSizePolicy(sizePolicy)
        self.configGroupBox.setMinimumSize(QtCore.QSize(0, 215))
        self.configGroupBox.setObjectName(_fromUtf8("configGroupBox"))
        self.gridLayoutWidget = QtGui.QWidget(self.configGroupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 761, 190))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.macAddress = QtGui.QLineEdit(self.gridLayoutWidget)
        self.macAddress.setObjectName(_fromUtf8("macAddress"))
        self.gridLayout_2.addWidget(self.macAddress, 1, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.configUpdateButton = QtGui.QPushButton(self.gridLayoutWidget)
        self.configUpdateButton.setObjectName(_fromUtf8("configUpdateButton"))
        self.horizontalLayout.addWidget(self.configUpdateButton)
        self.gridLayout_2.addLayout(self.horizontalLayout, 6, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.magicNumber = QtGui.QLabel(self.gridLayoutWidget)
        self.magicNumber.setText(_fromUtf8(""))
        self.magicNumber.setObjectName(_fromUtf8("magicNumber"))
        self.gridLayout_2.addWidget(self.magicNumber, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 0, 2, 1, 1)
        self.checksum = QtGui.QLabel(self.gridLayoutWidget)
        self.checksum.setText(_fromUtf8(""))
        self.checksum.setObjectName(_fromUtf8("checksum"))
        self.gridLayout_2.addWidget(self.checksum, 0, 3, 1, 1)
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 5, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.hwVersionMajor = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hwVersionMajor.sizePolicy().hasHeightForWidth())
        self.hwVersionMajor.setSizePolicy(sizePolicy)
        self.hwVersionMajor.setMinimumSize(QtCore.QSize(40, 0))
        self.hwVersionMajor.setMaximumSize(QtCore.QSize(40, 16777215))
        self.hwVersionMajor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.hwVersionMajor.setObjectName(_fromUtf8("hwVersionMajor"))
        self.horizontalLayout_2.addWidget(self.hwVersionMajor)
        self.label_17 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(5, 0))
        self.label_17.setMaximumSize(QtCore.QSize(5, 16777215))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_2.addWidget(self.label_17)
        self.hwVersionMinor = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hwVersionMinor.sizePolicy().hasHeightForWidth())
        self.hwVersionMinor.setSizePolicy(sizePolicy)
        self.hwVersionMinor.setMinimumSize(QtCore.QSize(40, 0))
        self.hwVersionMinor.setMaximumSize(QtCore.QSize(40, 16777215))
        self.hwVersionMinor.setObjectName(_fromUtf8("hwVersionMinor"))
        self.horizontalLayout_2.addWidget(self.hwVersionMinor)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_16 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_2.addWidget(self.label_16)
        self.fwVersionMajor = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fwVersionMajor.sizePolicy().hasHeightForWidth())
        self.fwVersionMajor.setSizePolicy(sizePolicy)
        self.fwVersionMajor.setMinimumSize(QtCore.QSize(40, 0))
        self.fwVersionMajor.setMaximumSize(QtCore.QSize(40, 16777215))
        self.fwVersionMajor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fwVersionMajor.setObjectName(_fromUtf8("fwVersionMajor"))
        self.horizontalLayout_2.addWidget(self.fwVersionMajor)
        self.label_18 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_2.addWidget(self.label_18)
        self.fwVersionMinor = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fwVersionMinor.sizePolicy().hasHeightForWidth())
        self.fwVersionMinor.setSizePolicy(sizePolicy)
        self.fwVersionMinor.setMinimumSize(QtCore.QSize(40, 0))
        self.fwVersionMinor.setMaximumSize(QtCore.QSize(40, 16777215))
        self.fwVersionMinor.setObjectName(_fromUtf8("fwVersionMinor"))
        self.horizontalLayout_2.addWidget(self.fwVersionMinor)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.label_19 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_2.addWidget(self.label_19)
        self.swVersionMajor = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.swVersionMajor.sizePolicy().hasHeightForWidth())
        self.swVersionMajor.setSizePolicy(sizePolicy)
        self.swVersionMajor.setMinimumSize(QtCore.QSize(40, 0))
        self.swVersionMajor.setMaximumSize(QtCore.QSize(40, 16777215))
        self.swVersionMajor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.swVersionMajor.setObjectName(_fromUtf8("swVersionMajor"))
        self.horizontalLayout_2.addWidget(self.swVersionMajor)
        self.label_21 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_2.addWidget(self.label_21)
        self.swVersionMinor = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.swVersionMinor.sizePolicy().hasHeightForWidth())
        self.swVersionMinor.setSizePolicy(sizePolicy)
        self.swVersionMinor.setMinimumSize(QtCore.QSize(40, 0))
        self.swVersionMinor.setMaximumSize(QtCore.QSize(40, 16777215))
        self.swVersionMinor.setObjectName(_fromUtf8("swVersionMinor"))
        self.horizontalLayout_2.addWidget(self.swVersionMinor)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 5, 1, 1, 3)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 3, 0, 1, 1)
        self.netMask = QtGui.QLineEdit(self.gridLayoutWidget)
        self.netMask.setObjectName(_fromUtf8("netMask"))
        self.gridLayout_2.addWidget(self.netMask, 3, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.ipAddress = QtGui.QLineEdit(self.gridLayoutWidget)
        self.ipAddress.setObjectName(_fromUtf8("ipAddress"))
        self.gridLayout_2.addWidget(self.ipAddress, 2, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 1, 2, 1, 1)
        self.boardId = QtGui.QLineEdit(self.gridLayoutWidget)
        self.boardId.setObjectName(_fromUtf8("boardId"))
        self.gridLayout_2.addWidget(self.boardId, 1, 3, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 4, 0, 1, 1)
        self.gateway = QtGui.QLineEdit(self.gridLayoutWidget)
        self.gateway.setObjectName(_fromUtf8("gateway"))
        self.gridLayout_2.addWidget(self.gateway, 4, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 2, 2, 1, 1)
        self.boardType = QtGui.QLineEdit(self.gridLayoutWidget)
        self.boardType.setObjectName(_fromUtf8("boardType"))
        self.gridLayout_2.addWidget(self.boardType, 2, 3, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 4, 2, 1, 1)
        self.critTempTreshold = QtGui.QLineEdit(self.gridLayoutWidget)
        self.critTempTreshold.setObjectName(_fromUtf8("critTempTreshold"))
        self.gridLayout_2.addWidget(self.critTempTreshold, 4, 3, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 3, 2, 1, 1)
        self.highTempThreshold = QtGui.QLineEdit(self.gridLayoutWidget)
        self.highTempThreshold.setObjectName(_fromUtf8("highTempThreshold"))
        self.gridLayout_2.addWidget(self.highTempThreshold, 3, 3, 1, 1)
        self.verticalLayout.addWidget(self.configGroupBox)
        spacerItem4 = QtGui.QSpacerItem(20, 150, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.messageBox = QtGui.QTextEdit(self.centralwidget)
        self.messageBox.setGeometry(QtCore.QRect(10, 550, 777, 192))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.messageBox.setFont(font)
        self.messageBox.setReadOnly(True)
        self.messageBox.setObjectName(_fromUtf8("messageBox"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.connectButton, self.connectAddr)
        MainWindow.setTabOrder(self.connectAddr, self.connectPort)
        MainWindow.setTabOrder(self.connectPort, self.macAddress)
        MainWindow.setTabOrder(self.macAddress, self.hwVersionMajor)
        MainWindow.setTabOrder(self.hwVersionMajor, self.hwVersionMinor)
        MainWindow.setTabOrder(self.hwVersionMinor, self.fwVersionMajor)
        MainWindow.setTabOrder(self.fwVersionMajor, self.fwVersionMinor)
        MainWindow.setTabOrder(self.fwVersionMinor, self.swVersionMajor)
        MainWindow.setTabOrder(self.swVersionMajor, self.swVersionMinor)
        MainWindow.setTabOrder(self.swVersionMinor, self.configUpdateButton)
        MainWindow.setTabOrder(self.configUpdateButton, self.messageBox)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "STFC FEM Control", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Address:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.connectButton.setText(QtGui.QApplication.translate("MainWindow", "  Connect  ", None, QtGui.QApplication.UnicodeUTF8))
        self.configGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "EEPROM Config", None, QtGui.QApplication.UnicodeUTF8))
        self.configUpdateButton.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Magic Number:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Checksum:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Hardware Version:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Firmware Version:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Software Version:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "MAC Address:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Netmask:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "IP Address:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Board ID:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Gateway:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Board Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Critical Temp Threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "High Temp Threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Messages:", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))

