# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Documents and Settings\ckd27546\workspace\excaliburPower\excaliburPowerGuiMain_ui.ui'
#
# Created: Mon Jan 30 15:45:17 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName(_fromUtf8("mainWindow"))
        mainWindow.resize(610, 660)
        mainWindow.setWindowTitle(QtGui.QApplication.translate("mainWindow", "excaliburPower", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 611, 631))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gbSetup = QtGui.QGroupBox(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbSetup.sizePolicy().hasHeightForWidth())
        self.gbSetup.setSizePolicy(sizePolicy)
        self.gbSetup.setMinimumSize(QtCore.QSize(0, 100))
        self.gbSetup.setMaximumSize(QtCore.QSize(608, 115))
        self.gbSetup.setTitle(QtGui.QApplication.translate("mainWindow", "Setup Features", None, QtGui.QApplication.UnicodeUTF8))
        self.gbSetup.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.gbSetup.setFlat(False)
        self.gbSetup.setObjectName(_fromUtf8("gbSetup"))
        self.lblSerialPort = QtGui.QLabel(self.gbSetup)
        self.lblSerialPort.setGeometry(QtCore.QRect(10, 10, 101, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lblSerialPort.setFont(font)
        self.lblSerialPort.setText(QtGui.QApplication.translate("mainWindow", "Select Serial Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSerialPort.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblSerialPort.setObjectName(_fromUtf8("lblSerialPort"))
        self.lwSerialPort = QtGui.QListWidget(self.gbSetup)
        self.lwSerialPort.setGeometry(QtCore.QRect(10, 30, 90, 61))
        self.lwSerialPort.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lwSerialPort.setAutoScroll(True)
        self.lwSerialPort.setEditTriggers(QtGui.QAbstractItemView.AllEditTriggers)
        self.lwSerialPort.setObjectName(_fromUtf8("lwSerialPort"))
        self.lePollingInterval = QtGui.QLineEdit(self.gbSetup)
        self.lePollingInterval.setEnabled(True)
        self.lePollingInterval.setGeometry(QtCore.QRect(550, 10, 41, 20))
        self.lePollingInterval.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lePollingInterval.setText(QtGui.QApplication.translate("mainWindow", "520.0", None, QtGui.QApplication.UnicodeUTF8))
        self.lePollingInterval.setObjectName(_fromUtf8("lePollingInterval"))
        self.cbPollingBox = QtGui.QCheckBox(self.gbSetup)
        self.cbPollingBox.setGeometry(QtCore.QRect(440, 10, 111, 18))
        self.cbPollingBox.setText(QtGui.QApplication.translate("mainWindow", "Enable polling (ms)", None, QtGui.QApplication.UnicodeUTF8))
        self.cbPollingBox.setChecked(True)
        self.cbPollingBox.setObjectName(_fromUtf8("cbPollingBox"))
        self.lblLEDtest_5 = QtGui.QLabel(self.gbSetup)
        self.lblLEDtest_5.setGeometry(QtCore.QRect(220, 80, 60, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lblLEDtest_5.setFont(font)
        self.lblLEDtest_5.setText(QtGui.QApplication.translate("mainWindow", "BIAS Status", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLEDtest_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblLEDtest_5.setObjectName(_fromUtf8("lblLEDtest_5"))
        self.lvButton = QtGui.QPushButton(self.gbSetup)
        self.lvButton.setGeometry(QtCore.QRect(120, 50, 70, 20))
        self.lvButton.setText(QtGui.QApplication.translate("mainWindow", "enable &LV", None, QtGui.QApplication.UnicodeUTF8))
        self.lvButton.setCheckable(False)
        self.lvButton.setObjectName(_fromUtf8("lvButton"))
        self.frmLowVoltageStatus = QtGui.QFrame(self.gbSetup)
        self.frmLowVoltageStatus.setGeometry(QtCore.QRect(200, 53, 13, 13))
        self.frmLowVoltageStatus.setAutoFillBackground(False)
        self.frmLowVoltageStatus.setStyleSheet(_fromUtf8("\n"
"background-color: rgb(255, 0, 0);"))
        self.frmLowVoltageStatus.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmLowVoltageStatus.setFrameShadow(QtGui.QFrame.Raised)
        self.frmLowVoltageStatus.setObjectName(_fromUtf8("frmLowVoltageStatus"))
        self.biasButton = QtGui.QPushButton(self.gbSetup)
        self.biasButton.setGeometry(QtCore.QRect(120, 80, 70, 20))
        self.biasButton.setText(QtGui.QApplication.translate("mainWindow", "enable &BIAS", None, QtGui.QApplication.UnicodeUTF8))
        self.biasButton.setCheckable(False)
        self.biasButton.setObjectName(_fromUtf8("biasButton"))
        self.frmBiasStatus = QtGui.QFrame(self.gbSetup)
        self.frmBiasStatus.setGeometry(QtCore.QRect(200, 83, 13, 13))
        self.frmBiasStatus.setAutoFillBackground(False)
        self.frmBiasStatus.setStyleSheet(_fromUtf8("\n"
"background-color: rgb(255, 0, 0);"))
        self.frmBiasStatus.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmBiasStatus.setFrameShadow(QtGui.QFrame.Raised)
        self.frmBiasStatus.setObjectName(_fromUtf8("frmBiasStatus"))
        self.lblLEDtest_6 = QtGui.QLabel(self.gbSetup)
        self.lblLEDtest_6.setGeometry(QtCore.QRect(220, 50, 60, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lblLEDtest_6.setFont(font)
        self.lblLEDtest_6.setText(QtGui.QApplication.translate("mainWindow", "LV Status", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLEDtest_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblLEDtest_6.setObjectName(_fromUtf8("lblLEDtest_6"))
        self.leBiasLevel = QtGui.QLineEdit(self.gbSetup)
        self.leBiasLevel.setEnabled(True)
        self.leBiasLevel.setGeometry(QtCore.QRect(180, 10, 41, 20))
        self.leBiasLevel.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.leBiasLevel.setText(QtGui.QApplication.translate("mainWindow", "150", None, QtGui.QApplication.UnicodeUTF8))
        self.leBiasLevel.setObjectName(_fromUtf8("leBiasLevel"))
        self.lblBiasLevel = QtGui.QLabel(self.gbSetup)
        self.lblBiasLevel.setGeometry(QtCore.QRect(120, 10, 51, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lblBiasLevel.setFont(font)
        self.lblBiasLevel.setText(QtGui.QApplication.translate("mainWindow", "Set Bias:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBiasLevel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblBiasLevel.setObjectName(_fromUtf8("lblBiasLevel"))
        self.leDivider = QtGui.QLineEdit(self.gbSetup)
        self.leDivider.setEnabled(True)
        self.leDivider.setGeometry(QtCore.QRect(110, 20, 2, 71))
        self.leDivider.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.leDivider.setText(_fromUtf8(""))
        self.leDivider.setObjectName(_fromUtf8("leDivider"))
        self.lblVoltages = QtGui.QLabel(self.gbSetup)
        self.lblVoltages.setGeometry(QtCore.QRect(120, 30, 151, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lblVoltages.setFont(font)
        self.lblVoltages.setText(QtGui.QApplication.translate("mainWindow", "Control Voltage Levels:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblVoltages.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblVoltages.setObjectName(_fromUtf8("lblVoltages"))
        self.leDivider_2 = QtGui.QLineEdit(self.gbSetup)
        self.leDivider_2.setEnabled(True)
        self.leDivider_2.setGeometry(QtCore.QRect(280, 20, 2, 71))
        self.leDivider_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.leDivider_2.setText(_fromUtf8(""))
        self.leDivider_2.setObjectName(_fromUtf8("leDivider_2"))
        self.lblLogFileLocation = QtGui.QLabel(self.gbSetup)
        self.lblLogFileLocation.setGeometry(QtCore.QRect(290, 10, 131, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lblLogFileLocation.setFont(font)
        self.lblLogFileLocation.setText(QtGui.QApplication.translate("mainWindow", "Change Log File Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLogFileLocation.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblLogFileLocation.setObjectName(_fromUtf8("lblLogFileLocation"))
        self.selectButton = QtGui.QPushButton(self.gbSetup)
        self.selectButton.setGeometry(QtCore.QRect(290, 30, 101, 20))
        self.selectButton.setText(QtGui.QApplication.translate("mainWindow", "&Change Location...", None, QtGui.QApplication.UnicodeUTF8))
        self.selectButton.setCheckable(False)
        self.selectButton.setObjectName(_fromUtf8("selectButton"))
        self.leSelectLogFileLocation = QtGui.QLineEdit(self.gbSetup)
        self.leSelectLogFileLocation.setEnabled(True)
        self.leSelectLogFileLocation.setGeometry(QtCore.QRect(290, 70, 301, 20))
        self.leSelectLogFileLocation.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.leSelectLogFileLocation.setText(QtGui.QApplication.translate("mainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.leSelectLogFileLocation.setObjectName(_fromUtf8("leSelectLogFileLocation"))
        self.lblCurrentFileName = QtGui.QLabel(self.gbSetup)
        self.lblCurrentFileName.setGeometry(QtCore.QRect(290, 50, 131, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lblCurrentFileName.setFont(font)
        self.lblCurrentFileName.setText(QtGui.QApplication.translate("mainWindow", "Current Log File Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCurrentFileName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblCurrentFileName.setObjectName(_fromUtf8("lblCurrentFileName"))
        self.horizontalLayout_2.addWidget(self.gbSetup)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gbPower = QtGui.QGroupBox(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbPower.sizePolicy().hasHeightForWidth())
        self.gbPower.setSizePolicy(sizePolicy)
        self.gbPower.setMinimumSize(QtCore.QSize(340, 350))
        self.gbPower.setMaximumSize(QtCore.QSize(250, 410))
        self.gbPower.setSizeIncrement(QtCore.QSize(0, 0))
        self.gbPower.setTitle(QtGui.QApplication.translate("mainWindow", "Power", None, QtGui.QApplication.UnicodeUTF8))
        self.gbPower.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.gbPower.setObjectName(_fromUtf8("gbPower"))
        self.gridLayoutWidget = QtGui.QWidget(self.gbPower)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 20, 351, 331))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.gridLayoutWidget.setFont(font)
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.le5VAV = QtGui.QLineEdit(self.gridLayoutWidget)
        self.le5VAV.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le5VAV.sizePolicy().hasHeightForWidth())
        self.le5VAV.setSizePolicy(sizePolicy)
        self.le5VAV.setMinimumSize(QtCore.QSize(60, 0))
        self.le5VAV.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le5VAV.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.le5VAV.setFont(font)
        self.le5VAV.setReadOnly(True)
        self.le5VAV.setObjectName(_fromUtf8("le5VAV"))
        self.gridLayout.addWidget(self.le5VAV, 1, 1, 1, 1)
        self.lblQuantity = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblQuantity.sizePolicy().hasHeightForWidth())
        self.lblQuantity.setSizePolicy(sizePolicy)
        self.lblQuantity.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lblQuantity.setFont(font)
        self.lblQuantity.setMouseTracking(False)
        self.lblQuantity.setText(QtGui.QApplication.translate("mainWindow", "Quantity", None, QtGui.QApplication.UnicodeUTF8))
        self.lblQuantity.setAlignment(QtCore.Qt.AlignCenter)
        self.lblQuantity.setObjectName(_fromUtf8("lblQuantity"))
        self.gridLayout.addWidget(self.lblQuantity, 0, 0, 1, 1)
        self.lbl5V_A = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl5V_A.sizePolicy().hasHeightForWidth())
        self.lbl5V_A.setSizePolicy(sizePolicy)
        self.lbl5V_A.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lbl5V_A.setFont(font)
        self.lbl5V_A.setText(QtGui.QApplication.translate("mainWindow", "5V_A", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl5V_A.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl5V_A.setObjectName(_fromUtf8("lbl5V_A"))
        self.gridLayout.addWidget(self.lbl5V_A, 1, 0, 1, 1)
        self.le5VBV = QtGui.QLineEdit(self.gridLayoutWidget)
        self.le5VBV.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le5VBV.sizePolicy().hasHeightForWidth())
        self.le5VBV.setSizePolicy(sizePolicy)
        self.le5VBV.setMinimumSize(QtCore.QSize(60, 0))
        self.le5VBV.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le5VBV.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.le5VBV.setFont(font)
        self.le5VBV.setText(_fromUtf8(""))
        self.le5VBV.setReadOnly(True)
        self.le5VBV.setObjectName(_fromUtf8("le5VBV"))
        self.gridLayout.addWidget(self.le5VBV, 1, 3, 1, 1)
        self.le5F0I = QtGui.QLineEdit(self.gridLayoutWidget)
        self.le5F0I.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le5F0I.sizePolicy().hasHeightForWidth())
        self.le5F0I.setSizePolicy(sizePolicy)
        self.le5F0I.setMinimumSize(QtCore.QSize(60, 0))
        self.le5F0I.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le5F0I.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.le5F0I.setFont(font)
        self.le5F0I.setReadOnly(True)
        self.le5F0I.setObjectName(_fromUtf8("le5F0I"))
        self.gridLayout.addWidget(self.le5F0I, 2, 1, 1, 1)
        self.le5F1I = QtGui.QLineEdit(self.gridLayoutWidget)
        self.le5F1I.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le5F1I.sizePolicy().hasHeightForWidth())
        self.le5F1I.setSizePolicy(sizePolicy)
        self.le5F1I.setMinimumSize(QtCore.QSize(60, 0))
        self.le5F1I.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le5F1I.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.le5F1I.setFont(font)
        self.le5F1I.setReadOnly(True)
        self.le5F1I.setObjectName(_fromUtf8("le5F1I"))
        self.gridLayout.addWidget(self.le5F1I, 2, 3, 1, 1)
        self.le5F2I = QtGui.QLineEdit(self.gridLayoutWidget)
        self.le5F2I.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le5F2I.sizePolicy().hasHeightForWidth())
        self.le5F2I.setSizePolicy(sizePolicy)
        self.le5F2I.setMinimumSize(QtCore.QSize(60, 0))
        self.le5F2I.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le5F2I.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.le5F2I.setFont(font)
        self.le5F2I.setReadOnly(True)
        self.le5F2I.setObjectName(_fromUtf8("le5F2I"))
        self.gridLayout.addWidget(self.le5F2I, 4, 1, 1, 1)
        self.le5F3I = QtGui.QLineEdit(self.gridLayoutWidget)
        self.le5F3I.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le5F3I.sizePolicy().hasHeightForWidth())
        self.le5F3I.setSizePolicy(sizePolicy)
        self.le5F3I.setMinimumSize(QtCore.QSize(60, 0))
        self.le5F3I.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le5F3I.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.le5F3I.setFont(font)
        self.le5F3I.setReadOnly(True)
        self.le5F3I.setObjectName(_fromUtf8("le5F3I"))
        self.gridLayout.addWidget(self.le5F3I, 4, 3, 1, 1)
        self.le5F4I = QtGui.QLineEdit(self.gridLayoutWidget)
        self.le5F4I.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le5F4I.sizePolicy().hasHeightForWidth())
        self.le5F4I.setSizePolicy(sizePolicy)
        self.le5F4I.setMinimumSize(QtCore.QSize(60, 0))
        self.le5F4I.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le5F4I.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.le5F4I.setFont(font)
        self.le5F4I.setReadOnly(True)
        self.le5F4I.setObjectName(_fromUtf8("le5F4I"))
        self.gridLayout.addWidget(self.le5F4I, 7, 1, 1, 1)
        self.le5F5I = QtGui.QLineEdit(self.gridLayoutWidget)
        self.le5F5I.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le5F5I.sizePolicy().hasHeightForWidth())
        self.le5F5I.setSizePolicy(sizePolicy)
        self.le5F5I.setMinimumSize(QtCore.QSize(60, 0))
        self.le5F5I.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le5F5I.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.le5F5I.setFont(font)
        self.le5F5I.setReadOnly(True)
        self.le5F5I.setObjectName(_fromUtf8("le5F5I"))
        self.gridLayout.addWidget(self.le5F5I, 7, 3, 1, 1)
        self.le18VAA = QtGui.QLineEdit(self.gridLayoutWidget)
        self.le18VAA.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le18VAA.sizePolicy().hasHeightForWidth())
        self.le18VAA.setSizePolicy(sizePolicy)
        self.le18VAA.setMinimumSize(QtCore.QSize(60, 0))
        self.le18VAA.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le18VAA.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.le18VAA.setFont(font)
        self.le18VAA.setReadOnly(True)
        self.le18VAA.setObjectName(_fromUtf8("le18VAA"))
        self.gridLayout.addWidget(self.le18VAA, 9, 1, 1, 1)
        self.le18VVA = QtGui.QLineEdit(self.gridLayoutWidget)
        self.le18VVA.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le18VVA.sizePolicy().hasHeightForWidth())
        self.le18VVA.setSizePolicy(sizePolicy)
        self.le18VVA.setMinimumSize(QtCore.QSize(60, 0))
        self.le18VVA.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le18VVA.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.le18VVA.setFont(font)
        self.le18VVA.setReadOnly(True)
        self.le18VVA.setObjectName(_fromUtf8("le18VVA"))
        self.gridLayout.addWidget(self.le18VVA, 9, 3, 1, 1)
        self.lbl18V_B = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl18V_B.sizePolicy().hasHeightForWidth())
        self.lbl18V_B.setSizePolicy(sizePolicy)
        self.lbl18V_B.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lbl18V_B.setFont(font)
        self.lbl18V_B.setText(QtGui.QApplication.translate("mainWindow", "1.8V_A", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl18V_B.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl18V_B.setObjectName(_fromUtf8("lbl18V_B"))
        self.gridLayout.addWidget(self.lbl18V_B, 9, 0, 1, 1)
        self.lbl18V_C = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl18V_C.sizePolicy().hasHeightForWidth())
        self.lbl18V_C.setSizePolicy(sizePolicy)
        self.lbl18V_C.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lbl18V_C.setFont(font)
        self.lbl18V_C.setText(QtGui.QApplication.translate("mainWindow", "1.8V_B", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl18V_C.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl18V_C.setObjectName(_fromUtf8("lbl18V_C"))
        self.gridLayout.addWidget(self.lbl18V_C, 10, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 11, 0, 1, 1)
        self.le18VAB = QtGui.QLineEdit(self.gridLayoutWidget)
        self.le18VAB.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le18VAB.sizePolicy().hasHeightForWidth())
        self.le18VAB.setSizePolicy(sizePolicy)
        self.le18VAB.setMinimumSize(QtCore.QSize(60, 0))
        self.le18VAB.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le18VAB.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.le18VAB.setFont(font)
        self.le18VAB.setReadOnly(True)
        self.le18VAB.setObjectName(_fromUtf8("le18VAB"))
        self.gridLayout.addWidget(self.le18VAB, 10, 1, 1, 1)
        self.le18VVB = QtGui.QLineEdit(self.gridLayoutWidget)
        self.le18VVB.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le18VVB.sizePolicy().hasHeightForWidth())
        self.le18VVB.setSizePolicy(sizePolicy)
        self.le18VVB.setMinimumSize(QtCore.QSize(60, 0))
        self.le18VVB.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le18VVB.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.le18VVB.setFont(font)
        self.le18VVB.setReadOnly(True)
        self.le18VVB.setObjectName(_fromUtf8("le18VVB"))
        self.gridLayout.addWidget(self.le18VVB, 10, 3, 1, 1)
        self.lbl33V = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl33V.sizePolicy().hasHeightForWidth())
        self.lbl33V.setSizePolicy(sizePolicy)
        self.lbl33V.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lbl33V.setFont(font)
        self.lbl33V.setText(QtGui.QApplication.translate("mainWindow", "3.3V", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl33V.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl33V.setObjectName(_fromUtf8("lbl33V"))
        self.gridLayout.addWidget(self.lbl33V, 12, 0, 1, 1)
        self.lbl200V = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl200V.sizePolicy().hasHeightForWidth())
        self.lbl200V.setSizePolicy(sizePolicy)
        self.lbl200V.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lbl200V.setFont(font)
        self.lbl200V.setText(QtGui.QApplication.translate("mainWindow", "200V", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl200V.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl200V.setObjectName(_fromUtf8("lbl200V"))
        self.gridLayout.addWidget(self.lbl200V, 13, 0, 1, 1)
        self.lbl48V = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl48V.sizePolicy().hasHeightForWidth())
        self.lbl48V.setSizePolicy(sizePolicy)
        self.lbl48V.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lbl48V.setFont(font)
        self.lbl48V.setText(QtGui.QApplication.translate("mainWindow", "48V", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl48V.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl48V.setObjectName(_fromUtf8("lbl48V"))
        self.gridLayout.addWidget(self.lbl48V, 14, 0, 1, 1)
        self.lbl5SUPERV = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl5SUPERV.sizePolicy().hasHeightForWidth())
        self.lbl5SUPERV.setSizePolicy(sizePolicy)
        self.lbl5SUPERV.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lbl5SUPERV.setFont(font)
        self.lbl5SUPERV.setText(QtGui.QApplication.translate("mainWindow", "5SUPERV", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl5SUPERV.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl5SUPERV.setObjectName(_fromUtf8("lbl5SUPERV"))
        self.gridLayout.addWidget(self.lbl5SUPERV, 15, 0, 1, 1)
        self.le33VV = QtGui.QLineEdit(self.gridLayoutWidget)
        self.le33VV.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le33VV.sizePolicy().hasHeightForWidth())
        self.le33VV.setSizePolicy(sizePolicy)
        self.le33VV.setMinimumSize(QtCore.QSize(60, 0))
        self.le33VV.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le33VV.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.le33VV.setFont(font)
        self.le33VV.setReadOnly(True)
        self.le33VV.setObjectName(_fromUtf8("le33VV"))
        self.gridLayout.addWidget(self.le33VV, 12, 1, 1, 1)
        self.le33VA = QtGui.QLineEdit(self.gridLayoutWidget)
        self.le33VA.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le33VA.sizePolicy().hasHeightForWidth())
        self.le33VA.setSizePolicy(sizePolicy)
        self.le33VA.setMinimumSize(QtCore.QSize(60, 0))
        self.le33VA.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le33VA.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.le33VA.setFont(font)
        self.le33VA.setReadOnly(True)
        self.le33VA.setObjectName(_fromUtf8("le33VA"))
        self.gridLayout.addWidget(self.le33VA, 12, 3, 1, 1)
        self.le200VV = QtGui.QLineEdit(self.gridLayoutWidget)
        self.le200VV.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le200VV.sizePolicy().hasHeightForWidth())
        self.le200VV.setSizePolicy(sizePolicy)
        self.le200VV.setMinimumSize(QtCore.QSize(60, 0))
        self.le200VV.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le200VV.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.le200VV.setFont(font)
        self.le200VV.setReadOnly(True)
        self.le200VV.setObjectName(_fromUtf8("le200VV"))
        self.gridLayout.addWidget(self.le200VV, 13, 1, 1, 1)
        self.le200VA = QtGui.QLineEdit(self.gridLayoutWidget)
        self.le200VA.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le200VA.sizePolicy().hasHeightForWidth())
        self.le200VA.setSizePolicy(sizePolicy)
        self.le200VA.setMinimumSize(QtCore.QSize(60, 0))
        self.le200VA.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le200VA.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.le200VA.setFont(font)
        self.le200VA.setReadOnly(True)
        self.le200VA.setObjectName(_fromUtf8("le200VA"))
        self.gridLayout.addWidget(self.le200VA, 13, 3, 1, 1)
        self.le48VV = QtGui.QLineEdit(self.gridLayoutWidget)
        self.le48VV.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le48VV.sizePolicy().hasHeightForWidth())
        self.le48VV.setSizePolicy(sizePolicy)
        self.le48VV.setMinimumSize(QtCore.QSize(60, 0))
        self.le48VV.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le48VV.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.le48VV.setFont(font)
        self.le48VV.setReadOnly(True)
        self.le48VV.setObjectName(_fromUtf8("le48VV"))
        self.gridLayout.addWidget(self.le48VV, 14, 1, 1, 1)
        self.le48VA = QtGui.QLineEdit(self.gridLayoutWidget)
        self.le48VA.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le48VA.sizePolicy().hasHeightForWidth())
        self.le48VA.setSizePolicy(sizePolicy)
        self.le48VA.setMinimumSize(QtCore.QSize(60, 0))
        self.le48VA.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le48VA.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.le48VA.setFont(font)
        self.le48VA.setReadOnly(True)
        self.le48VA.setObjectName(_fromUtf8("le48VA"))
        self.gridLayout.addWidget(self.le48VA, 14, 3, 1, 1)
        self.le5SUPERVV = QtGui.QLineEdit(self.gridLayoutWidget)
        self.le5SUPERVV.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le5SUPERVV.sizePolicy().hasHeightForWidth())
        self.le5SUPERVV.setSizePolicy(sizePolicy)
        self.le5SUPERVV.setMinimumSize(QtCore.QSize(60, 0))
        self.le5SUPERVV.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le5SUPERVV.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.le5SUPERVV.setFont(font)
        self.le5SUPERVV.setReadOnly(True)
        self.le5SUPERVV.setObjectName(_fromUtf8("le5SUPERVV"))
        self.gridLayout.addWidget(self.le5SUPERVV, 15, 1, 1, 1)
        self.le5SUPERVA = QtGui.QLineEdit(self.gridLayoutWidget)
        self.le5SUPERVA.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le5SUPERVA.sizePolicy().hasHeightForWidth())
        self.le5SUPERVA.setSizePolicy(sizePolicy)
        self.le5SUPERVA.setMinimumSize(QtCore.QSize(60, 0))
        self.le5SUPERVA.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le5SUPERVA.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.le5SUPERVA.setFont(font)
        self.le5SUPERVA.setReadOnly(True)
        self.le5SUPERVA.setObjectName(_fromUtf8("le5SUPERVA"))
        self.gridLayout.addWidget(self.le5SUPERVA, 15, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 8, 0, 1, 1)
        self.lbl5V_B = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl5V_B.sizePolicy().hasHeightForWidth())
        self.lbl5V_B.setSizePolicy(sizePolicy)
        self.lbl5V_B.setMinimumSize(QtCore.QSize(50, 0))
        self.lbl5V_B.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lbl5V_B.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lbl5V_B.setFont(font)
        self.lbl5V_B.setText(QtGui.QApplication.translate("mainWindow", "5V_B", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl5V_B.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl5V_B.setObjectName(_fromUtf8("lbl5V_B"))
        self.gridLayout.addWidget(self.lbl5V_B, 1, 2, 1, 1)
        self.lbl5VF0 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl5VF0.sizePolicy().hasHeightForWidth())
        self.lbl5VF0.setSizePolicy(sizePolicy)
        self.lbl5VF0.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lbl5VF0.setFont(font)
        self.lbl5VF0.setText(QtGui.QApplication.translate("mainWindow", "5V_FEM0", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl5VF0.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl5VF0.setObjectName(_fromUtf8("lbl5VF0"))
        self.gridLayout.addWidget(self.lbl5VF0, 2, 0, 1, 1)
        self.lbl5VF2 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl5VF2.sizePolicy().hasHeightForWidth())
        self.lbl5VF2.setSizePolicy(sizePolicy)
        self.lbl5VF2.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lbl5VF2.setFont(font)
        self.lbl5VF2.setText(QtGui.QApplication.translate("mainWindow", "5V_FEM2", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl5VF2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl5VF2.setObjectName(_fromUtf8("lbl5VF2"))
        self.gridLayout.addWidget(self.lbl5VF2, 4, 0, 1, 1)
        self.lbl5VF4 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl5VF4.sizePolicy().hasHeightForWidth())
        self.lbl5VF4.setSizePolicy(sizePolicy)
        self.lbl5VF4.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lbl5VF4.setFont(font)
        self.lbl5VF4.setText(QtGui.QApplication.translate("mainWindow", "5V_FEM4", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl5VF4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl5VF4.setObjectName(_fromUtf8("lbl5VF4"))
        self.gridLayout.addWidget(self.lbl5VF4, 7, 0, 1, 1)
        self.lbl5VF1 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl5VF1.sizePolicy().hasHeightForWidth())
        self.lbl5VF1.setSizePolicy(sizePolicy)
        self.lbl5VF1.setMinimumSize(QtCore.QSize(50, 0))
        self.lbl5VF1.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lbl5VF1.setFont(font)
        self.lbl5VF1.setText(QtGui.QApplication.translate("mainWindow", "5V_FEM1", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl5VF1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl5VF1.setObjectName(_fromUtf8("lbl5VF1"))
        self.gridLayout.addWidget(self.lbl5VF1, 2, 2, 1, 1)
        self.lbl5VF3 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl5VF3.sizePolicy().hasHeightForWidth())
        self.lbl5VF3.setSizePolicy(sizePolicy)
        self.lbl5VF3.setMinimumSize(QtCore.QSize(50, 0))
        self.lbl5VF3.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lbl5VF3.setFont(font)
        self.lbl5VF3.setText(QtGui.QApplication.translate("mainWindow", "5V_FEM3", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl5VF3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl5VF3.setObjectName(_fromUtf8("lbl5VF3"))
        self.gridLayout.addWidget(self.lbl5VF3, 4, 2, 1, 1)
        self.lbl5VF5 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl5VF5.sizePolicy().hasHeightForWidth())
        self.lbl5VF5.setSizePolicy(sizePolicy)
        self.lbl5VF5.setMinimumSize(QtCore.QSize(50, 0))
        self.lbl5VF5.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lbl5VF5.setFont(font)
        self.lbl5VF5.setText(QtGui.QApplication.translate("mainWindow", "5V_FEM5", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl5VF5.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl5VF5.setObjectName(_fromUtf8("lbl5VF5"))
        self.gridLayout.addWidget(self.lbl5VF5, 7, 2, 1, 1)
        self.lblVoltage = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblVoltage.sizePolicy().hasHeightForWidth())
        self.lblVoltage.setSizePolicy(sizePolicy)
        self.lblVoltage.setMinimumSize(QtCore.QSize(60, 0))
        self.lblVoltage.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lblVoltage.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lblVoltage.setFont(font)
        self.lblVoltage.setMouseTracking(False)
        self.lblVoltage.setText(QtGui.QApplication.translate("mainWindow", "Voltage [V]", None, QtGui.QApplication.UnicodeUTF8))
        self.lblVoltage.setAlignment(QtCore.Qt.AlignCenter)
        self.lblVoltage.setObjectName(_fromUtf8("lblVoltage"))
        self.gridLayout.addWidget(self.lblVoltage, 8, 1, 1, 1)
        self.lblCurrent = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCurrent.sizePolicy().hasHeightForWidth())
        self.lblCurrent.setSizePolicy(sizePolicy)
        self.lblCurrent.setMinimumSize(QtCore.QSize(60, 0))
        self.lblCurrent.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lblCurrent.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lblCurrent.setFont(font)
        self.lblCurrent.setMouseTracking(False)
        self.lblCurrent.setText(QtGui.QApplication.translate("mainWindow", "Current [A]", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCurrent.setObjectName(_fromUtf8("lblCurrent"))
        self.gridLayout.addWidget(self.lblCurrent, 8, 3, 1, 1)
        self.lblQuantity_2 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblQuantity_2.sizePolicy().hasHeightForWidth())
        self.lblQuantity_2.setSizePolicy(sizePolicy)
        self.lblQuantity_2.setMinimumSize(QtCore.QSize(50, 0))
        self.lblQuantity_2.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lblQuantity_2.setFont(font)
        self.lblQuantity_2.setMouseTracking(False)
        self.lblQuantity_2.setText(QtGui.QApplication.translate("mainWindow", "Quantity", None, QtGui.QApplication.UnicodeUTF8))
        self.lblQuantity_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblQuantity_2.setObjectName(_fromUtf8("lblQuantity_2"))
        self.gridLayout.addWidget(self.lblQuantity_2, 0, 2, 1, 1)
        self.horizontalLayout.addWidget(self.gbPower)
        self.gbMonitor = QtGui.QGroupBox(self.verticalLayoutWidget)
        self.gbMonitor.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbMonitor.sizePolicy().hasHeightForWidth())
        self.gbMonitor.setSizePolicy(sizePolicy)
        self.gbMonitor.setMinimumSize(QtCore.QSize(270, 360))
        self.gbMonitor.setMaximumSize(QtCore.QSize(100, 410))
        self.gbMonitor.setSizeIncrement(QtCore.QSize(0, 0))
        self.gbMonitor.setTitle(QtGui.QApplication.translate("mainWindow", "Monitor", None, QtGui.QApplication.UnicodeUTF8))
        self.gbMonitor.setObjectName(_fromUtf8("gbMonitor"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.gbMonitor)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 251, 331))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblHum_mon = QtGui.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblHum_mon.sizePolicy().hasHeightForWidth())
        self.lblHum_mon.setSizePolicy(sizePolicy)
        self.lblHum_mon.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lblHum_mon.setFont(font)
        self.lblHum_mon.setText(QtGui.QApplication.translate("mainWindow", "Hum_mon [%]", None, QtGui.QApplication.UnicodeUTF8))
        self.lblHum_mon.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHum_mon.setObjectName(_fromUtf8("lblHum_mon"))
        self.gridLayout_2.addWidget(self.lblHum_mon, 0, 0, 1, 1)
        self.lblHum_stat = QtGui.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblHum_stat.sizePolicy().hasHeightForWidth())
        self.lblHum_stat.setSizePolicy(sizePolicy)
        self.lblHum_stat.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lblHum_stat.setFont(font)
        self.lblHum_stat.setText(QtGui.QApplication.translate("mainWindow", "Hum_Stat [B]", None, QtGui.QApplication.UnicodeUTF8))
        self.lblHum_stat.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHum_stat.setObjectName(_fromUtf8("lblHum_stat"))
        self.gridLayout_2.addWidget(self.lblHum_stat, 1, 0, 1, 1)
        self.lblAirtmp_mon = QtGui.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAirtmp_mon.sizePolicy().hasHeightForWidth())
        self.lblAirtmp_mon.setSizePolicy(sizePolicy)
        self.lblAirtmp_mon.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lblAirtmp_mon.setFont(font)
        self.lblAirtmp_mon.setText(QtGui.QApplication.translate("mainWindow", "Air_temp_mon [C]", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAirtmp_mon.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAirtmp_mon.setObjectName(_fromUtf8("lblAirtmp_mon"))
        self.gridLayout_2.addWidget(self.lblAirtmp_mon, 6, 0, 1, 1)
        self.leHum_mon = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.leHum_mon.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leHum_mon.sizePolicy().hasHeightForWidth())
        self.leHum_mon.setSizePolicy(sizePolicy)
        self.leHum_mon.setMinimumSize(QtCore.QSize(0, 0))
        self.leHum_mon.setMaximumSize(QtCore.QSize(60, 16777215))
        self.leHum_mon.setReadOnly(True)
        self.leHum_mon.setObjectName(_fromUtf8("leHum_mon"))
        self.gridLayout_2.addWidget(self.leHum_mon, 0, 2, 1, 1)
        self.leAirtmp_mon = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.leAirtmp_mon.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leAirtmp_mon.sizePolicy().hasHeightForWidth())
        self.leAirtmp_mon.setSizePolicy(sizePolicy)
        self.leAirtmp_mon.setMinimumSize(QtCore.QSize(0, 0))
        self.leAirtmp_mon.setMaximumSize(QtCore.QSize(60, 16777215))
        self.leAirtmp_mon.setReadOnly(True)
        self.leAirtmp_mon.setObjectName(_fromUtf8("leAirtmp_mon"))
        self.gridLayout_2.addWidget(self.leAirtmp_mon, 6, 2, 1, 1)
        self.lblAirtmp_stat = QtGui.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAirtmp_stat.sizePolicy().hasHeightForWidth())
        self.lblAirtmp_stat.setSizePolicy(sizePolicy)
        self.lblAirtmp_stat.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lblAirtmp_stat.setFont(font)
        self.lblAirtmp_stat.setMouseTracking(False)
        self.lblAirtmp_stat.setText(QtGui.QApplication.translate("mainWindow", "Air_temp_stat [B]", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAirtmp_stat.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAirtmp_stat.setObjectName(_fromUtf8("lblAirtmp_stat"))
        self.gridLayout_2.addWidget(self.lblAirtmp_stat, 8, 0, 1, 1)
        self.lblCoolant_flow_mon = QtGui.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCoolant_flow_mon.sizePolicy().hasHeightForWidth())
        self.lblCoolant_flow_mon.setSizePolicy(sizePolicy)
        self.lblCoolant_flow_mon.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lblCoolant_flow_mon.setFont(font)
        self.lblCoolant_flow_mon.setText(QtGui.QApplication.translate("mainWindow", "Coolant_flow_mon [L/min]", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCoolant_flow_mon.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCoolant_flow_mon.setObjectName(_fromUtf8("lblCoolant_flow_mon"))
        self.gridLayout_2.addWidget(self.lblCoolant_flow_mon, 11, 0, 1, 1)
        self.lblCoolont_flow_stat = QtGui.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCoolont_flow_stat.sizePolicy().hasHeightForWidth())
        self.lblCoolont_flow_stat.setSizePolicy(sizePolicy)
        self.lblCoolont_flow_stat.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lblCoolont_flow_stat.setFont(font)
        self.lblCoolont_flow_stat.setText(QtGui.QApplication.translate("mainWindow", "Coolont_flow_status [B]", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCoolont_flow_stat.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCoolont_flow_stat.setObjectName(_fromUtf8("lblCoolont_flow_stat"))
        self.gridLayout_2.addWidget(self.lblCoolont_flow_stat, 12, 0, 1, 1)
        self.lblCoolant_temp_mon = QtGui.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCoolant_temp_mon.sizePolicy().hasHeightForWidth())
        self.lblCoolant_temp_mon.setSizePolicy(sizePolicy)
        self.lblCoolant_temp_mon.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lblCoolant_temp_mon.setFont(font)
        self.lblCoolant_temp_mon.setText(QtGui.QApplication.translate("mainWindow", "Coolant_temp_mon [C]", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCoolant_temp_mon.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCoolant_temp_mon.setObjectName(_fromUtf8("lblCoolant_temp_mon"))
        self.gridLayout_2.addWidget(self.lblCoolant_temp_mon, 15, 0, 1, 1)
        self.lblCoolant_temp_stat = QtGui.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCoolant_temp_stat.sizePolicy().hasHeightForWidth())
        self.lblCoolant_temp_stat.setSizePolicy(sizePolicy)
        self.lblCoolant_temp_stat.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lblCoolant_temp_stat.setFont(font)
        self.lblCoolant_temp_stat.setText(QtGui.QApplication.translate("mainWindow", "Coolant_temp_stat [B]", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCoolant_temp_stat.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCoolant_temp_stat.setObjectName(_fromUtf8("lblCoolant_temp_stat"))
        self.gridLayout_2.addWidget(self.lblCoolant_temp_stat, 17, 0, 1, 1)
        self.leCoolant_flow_mon = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.leCoolant_flow_mon.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leCoolant_flow_mon.sizePolicy().hasHeightForWidth())
        self.leCoolant_flow_mon.setSizePolicy(sizePolicy)
        self.leCoolant_flow_mon.setMinimumSize(QtCore.QSize(0, 0))
        self.leCoolant_flow_mon.setMaximumSize(QtCore.QSize(60, 16777215))
        self.leCoolant_flow_mon.setReadOnly(True)
        self.leCoolant_flow_mon.setObjectName(_fromUtf8("leCoolant_flow_mon"))
        self.gridLayout_2.addWidget(self.leCoolant_flow_mon, 11, 2, 1, 1)
        self.leCoolant_stat = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.leCoolant_stat.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leCoolant_stat.sizePolicy().hasHeightForWidth())
        self.leCoolant_stat.setSizePolicy(sizePolicy)
        self.leCoolant_stat.setMinimumSize(QtCore.QSize(0, 0))
        self.leCoolant_stat.setMaximumSize(QtCore.QSize(60, 16777215))
        self.leCoolant_stat.setReadOnly(True)
        self.leCoolant_stat.setObjectName(_fromUtf8("leCoolant_stat"))
        self.gridLayout_2.addWidget(self.leCoolant_stat, 15, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 13, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 10, 0, 1, 1)
        self.frmHumidityStatus = QtGui.QFrame(self.gridLayoutWidget_2)
        self.frmHumidityStatus.setAutoFillBackground(False)
        self.frmHumidityStatus.setStyleSheet(_fromUtf8("\n"
"background-color: rgb(0, 255, 0);"))
        self.frmHumidityStatus.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmHumidityStatus.setFrameShadow(QtGui.QFrame.Raised)
        self.frmHumidityStatus.setObjectName(_fromUtf8("frmHumidityStatus"))
        self.gridLayout_2.addWidget(self.frmHumidityStatus, 1, 2, 1, 1)
        self.frmAirTempStatus = QtGui.QFrame(self.gridLayoutWidget_2)
        self.frmAirTempStatus.setAutoFillBackground(False)
        self.frmAirTempStatus.setStyleSheet(_fromUtf8("\n"
"background-color: rgb(0, 255, 0);"))
        self.frmAirTempStatus.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmAirTempStatus.setFrameShadow(QtGui.QFrame.Raised)
        self.frmAirTempStatus.setObjectName(_fromUtf8("frmAirTempStatus"))
        self.gridLayout_2.addWidget(self.frmAirTempStatus, 8, 2, 1, 1)
        self.frmCoolantFlowStatus = QtGui.QFrame(self.gridLayoutWidget_2)
        self.frmCoolantFlowStatus.setAutoFillBackground(False)
        self.frmCoolantFlowStatus.setStyleSheet(_fromUtf8("\n"
"background-color: rgb(0, 255, 0);"))
        self.frmCoolantFlowStatus.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmCoolantFlowStatus.setFrameShadow(QtGui.QFrame.Raised)
        self.frmCoolantFlowStatus.setObjectName(_fromUtf8("frmCoolantFlowStatus"))
        self.gridLayout_2.addWidget(self.frmCoolantFlowStatus, 12, 2, 1, 1)
        self.frmCoolantTempStatus = QtGui.QFrame(self.gridLayoutWidget_2)
        self.frmCoolantTempStatus.setAutoFillBackground(False)
        self.frmCoolantTempStatus.setStyleSheet(_fromUtf8("\n"
"background-color: rgb(0, 255, 0);"))
        self.frmCoolantTempStatus.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmCoolantTempStatus.setFrameShadow(QtGui.QFrame.Raised)
        self.frmCoolantTempStatus.setObjectName(_fromUtf8("frmCoolantTempStatus"))
        self.gridLayout_2.addWidget(self.frmCoolantTempStatus, 17, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 2, 0, 1, 1)
        self.FrmFanFault = QtGui.QFrame(self.gridLayoutWidget_2)
        self.FrmFanFault.setAutoFillBackground(False)
        self.FrmFanFault.setStyleSheet(_fromUtf8("\n"
"background-color: rgb(0, 255, 0);"))
        self.FrmFanFault.setFrameShape(QtGui.QFrame.StyledPanel)
        self.FrmFanFault.setFrameShadow(QtGui.QFrame.Raised)
        self.FrmFanFault.setObjectName(_fromUtf8("FrmFanFault"))
        self.gridLayout_2.addWidget(self.FrmFanFault, 18, 2, 1, 1)
        self.lblFanFault = QtGui.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFanFault.sizePolicy().hasHeightForWidth())
        self.lblFanFault.setSizePolicy(sizePolicy)
        self.lblFanFault.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lblFanFault.setFont(font)
        self.lblFanFault.setText(QtGui.QApplication.translate("mainWindow", "Fan_Fault", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFanFault.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFanFault.setObjectName(_fromUtf8("lblFanFault"))
        self.gridLayout_2.addWidget(self.lblFanFault, 18, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 19, 0, 1, 1)
        self.horizontalLayout.addWidget(self.gbMonitor)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gbDebug = QtGui.QGroupBox(self.verticalLayoutWidget)
        self.gbDebug.setMaximumSize(QtCore.QSize(16777215, 60))
        self.gbDebug.setTitle(QtGui.QApplication.translate("mainWindow", "Debug Features (Only available when polling disabled)", None, QtGui.QApplication.UnicodeUTF8))
        self.gbDebug.setObjectName(_fromUtf8("gbDebug"))
        self.leDebugOutput = QtGui.QLineEdit(self.gbDebug)
        self.leDebugOutput.setEnabled(True)
        self.leDebugOutput.setGeometry(QtCore.QRect(440, 20, 160, 20))
        self.leDebugOutput.setText(QtGui.QApplication.translate("mainWindow", "Debug Output", None, QtGui.QApplication.UnicodeUTF8))
        self.leDebugOutput.setReadOnly(True)
        self.leDebugOutput.setObjectName(_fromUtf8("leDebugOutput"))
        self.leDebugInput = QtGui.QLineEdit(self.gbDebug)
        self.leDebugInput.setEnabled(True)
        self.leDebugInput.setGeometry(QtCore.QRect(110, 20, 111, 20))
        self.leDebugInput.setText(QtGui.QApplication.translate("mainWindow", "r 75 2 @", None, QtGui.QApplication.UnicodeUTF8))
        self.leDebugInput.setObjectName(_fromUtf8("leDebugInput"))
        self.debugButton = QtGui.QPushButton(self.gbDebug)
        self.debugButton.setGeometry(QtCore.QRect(230, 20, 75, 20))
        self.debugButton.setText(QtGui.QApplication.translate("mainWindow", "&Debug Send", None, QtGui.QApplication.UnicodeUTF8))
        self.debugButton.setCheckable(False)
        self.debugButton.setObjectName(_fromUtf8("debugButton"))
        self.lblDebugSend = QtGui.QLabel(self.gbDebug)
        self.lblDebugSend.setGeometry(QtCore.QRect(10, 20, 101, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lblDebugSend.setFont(font)
        self.lblDebugSend.setText(QtGui.QApplication.translate("mainWindow", "Send I2C Command:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDebugSend.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblDebugSend.setObjectName(_fromUtf8("lblDebugSend"))
        self.lblDebugReceive = QtGui.QLabel(self.gbDebug)
        self.lblDebugReceive.setGeometry(QtCore.QRect(320, 20, 121, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lblDebugReceive.setFont(font)
        self.lblDebugReceive.setText(QtGui.QApplication.translate("mainWindow", "Received I2C Command:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDebugReceive.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblDebugReceive.setObjectName(_fromUtf8("lblDebugReceive"))
        self.verticalLayout.addWidget(self.gbDebug)
        self.gbError = QtGui.QGroupBox(self.verticalLayoutWidget)
        self.gbError.setMaximumSize(QtCore.QSize(16777215, 80))
        self.gbError.setTitle(QtGui.QApplication.translate("mainWindow", "Error messages", None, QtGui.QApplication.UnicodeUTF8))
        self.gbError.setObjectName(_fromUtf8("gbError"))
        self.mbErrorMessages = QtGui.QTextEdit(self.gbError)
        self.mbErrorMessages.setGeometry(QtCore.QRect(10, 14, 590, 54))
        self.mbErrorMessages.setReadOnly(True)
        self.mbErrorMessages.setObjectName(_fromUtf8("mbErrorMessages"))
        self.verticalLayout.addWidget(self.gbError)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 610, 18))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setTitle(QtGui.QApplication.translate("mainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        mainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(mainWindow)
        self.actionQuit.setText(QtGui.QApplication.translate("mainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("triggered()")), mainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        pass

